presubmits:
  kubernetes-sigs/sig-storage-lib-external-provisioner:
  - name: pull-ibm-vpc-block-csi-driver-build
    always_run: true
    decorate: true
    skip_branches:
    - gh-pages
    path_alias: sigs.k8s.io/ibm-vpc-block-csi-driver
    annotations:
      testgrid-dashboards: sig-cloud-provider-ibm-vpc-block-csi-driver
      testgrid-tab-name: build
      description: Build test in ibm-vpc-block-csi-driver repo.
    spec:
      containers:
      - image: golang:1.15
        command:
        - make

  - name: pull-ibm-vpc-block-csi-driver-unit
    always_run: true
    decorate: true
    skip_branches:
    - gh-pages
    path_alias: sigs.k8s.io/ibm-vpc-block-csi-driver
    annotations:
      testgrid-dashboards: sig-cloud-provider-ibm-vpc-block-csi-driver
      testgrid-tab-name: unit
      description: Unit tests in ibm-vpc-block-csi-driver repo.
    spec:
      containers:
      - image: golang:1.15
        command:
        - make
        args:
        - test
