periodics:
- interval: 30m
  name: ci-kops-build
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20210428-a1a20d1-experimental
      args:
      - --repo=k8s.io/kops
      - --repo=k8s.io/release
      - --root=/go/src
      - --timeout=30
      - --scenario=execute
      - --
      - make
      - gcs-publish-ci
      - GCS_LOCATION=gs://kops-ci/bin
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, kops-presubmits
    testgrid-tab-name: kops-build
    testgrid-alert-email: release-team@kubernetes.io
- interval: 2h
  name: e2e-kops-aws-misc-upgrade
  always_run: false
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-dind-enabled: "true"
    preset-e2e-platform-aws: "true"
  decorate: true
  decoration_config:
    timeout: 2h
  extra_refs:
  - org: kubernetes
    repo: kops
    base_ref: master
    workdir: true
    path_alias: k8s.io/kops
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:latest-experimental
      imagePullPolicy: Always
      command:
      - runner.sh
      args:
      - ./tests/e2e/scenarios/k8s-upgrade/run-test.sh
      env:
      - name: CLOUD_PROVIDER
        value: aws
      - name: CLUSTER_NAME
        value: e2e-f9b0e6b3f9-bb3c3.test-cncf-aws.k8s.io
      - name: KOPS_STATE_STORE
        value: s3://k8s-kops-prow
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "6Gi"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-misc, kops-kubetest2
    testgrid-days-of-results: "30"
    testgrid-tab-name: kops-aws-upgrade
- interval: 2h
  name: e2e-kops-aws-misc-kops-upgrade
  always_run: false
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-dind-enabled: "true"
    preset-e2e-platform-aws: "true"
  decorate: true
  decoration_config:
    timeout: 2h
  extra_refs:
  - org: kubernetes
    repo: kops
    base_ref: master
    workdir: true
    path_alias: k8s.io/kops
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:latest-experimental
      imagePullPolicy: Always
      command:
      - runner.sh
      args:
      - ./tests/e2e/scenarios/kops-upgrade/run-test.sh
      - v1.20.0 # kops version
      - v1.20.6 # k8s version
      env:
      - name: CLOUD_PROVIDER
        value: aws
      - name: CLUSTER_NAME
        value: e2e-f9b0e6b3f9-a6ae4.test-cncf-aws.k8s.io
      - name: KOPS_STATE_STORE
        value: s3://k8s-kops-prow
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "6Gi"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-misc, kops-kubetest2
    testgrid-days-of-results: "30"
    testgrid-tab-name: kops-aws-kops-upgrade
- interval: 1h # TODO(justinsb): reduce once working
  name: e2e-kops-aws-upgrade-ko118-to-ko119
  always_run: false
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-dind-enabled: "true"
    preset-e2e-platform-aws: "true"
  decorate: true
  decoration_config:
    timeout: 2h
  extra_refs:
  - org: kubernetes
    repo: kops
    base_ref: master
    workdir: true
    path_alias: k8s.io/kops
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:latest-experimental
      imagePullPolicy: Always
      command:
      - runner.sh
      args:
      - ./tests/e2e/scenarios/upgrade-ab/run-test.sh
      env:
      - name: CLOUD_PROVIDER
        value: aws
      - name: CLUSTER_NAME
        value: e2e-f9b0e6b3f9-a6ae4.test-cncf-aws.k8s.io
      - name: KOPS_STATE_STORE
        value: s3://k8s-kops-prow
      - name: KOPS_VERSION_A
        value: v1.18.3
      - name: KOPS_VERSION_B
        value: v1.19.2
      - name: K8S_VERSION_A
        value: v1.18.18
      - name: K8S_VERSION_B
        value: v1.18.18
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "6Gi"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-misc, kops-kubetest2
    testgrid-days-of-results: "30"
    testgrid-tab-name: kops-aws-upgrade-ko118-to-ko119
- interval: 1h # TODO(justinsb): reduce once working
  name: e2e-kops-aws-upgrade-k119-ko119-to-k120-ko120
  always_run: false
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-dind-enabled: "true"
    preset-e2e-platform-aws: "true"
  decorate: true
  decoration_config:
    timeout: 2h
  extra_refs:
  - org: kubernetes
    repo: kops
    base_ref: master
    workdir: true
    path_alias: k8s.io/kops
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:latest-experimental
      imagePullPolicy: Always
      command:
      - runner.sh
      args:
      - ./tests/e2e/scenarios/upgrade-ab/run-test.sh
      env:
      - name: CLOUD_PROVIDER
        value: aws
      - name: CLUSTER_NAME
        value: e2e-f9b0e6b3f9-a6ae4.test-cncf-aws.k8s.io
      - name: KOPS_STATE_STORE
        value: s3://k8s-kops-prow
      - name: KOPS_VERSION_A
        value: v1.19.2
      - name: KOPS_VERSION_B
        value: v1.20.0
      - name: K8S_VERSION_A
        value: v1.19.10
      - name: K8S_VERSION_B
        value: v1.20.6
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "6Gi"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-misc, kops-kubetest2
    testgrid-days-of-results: "30"
    testgrid-tab-name: kops-aws-upgrade-k119-ko119-to-k120-ko120
