presets:
# Credentials for using DigitalOcean Spaces test account. Used for kops tests.
- labels:
    preset-do-spaces-credential: "true"
  env:
  - name: S3_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: spaces-digitalocean-s3
        key: access-key
  - name: S3_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: spaces-digitalocean-s3
        key: secret-key
