presubmits:
  kubernetes/kops:
  - name: pull-kops-e2e-kubernetes-aws-podutils
    branches:
    - master
    optional: true
    labels:
      preset-service-account: "true"
      preset-aws-ssh: "true"
      preset-aws-credential: "true"
      preset-dind-enabled: "true"
      preset-e2e-platform-aws: "true"
    decorate: true
    decoration_config:
      timeout: 90m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200107-164c5e8-experimental
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --aws
        - --aws-cluster-domain=test-cncf-aws.k8s.io
        - --check-leaked-resources=false
        - --cluster=
        - --extract=ci/latest
        - --ginkgo-parallel
        - --kops-build
        - --provider=aws
        - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort
        - --timeout=55m
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"
    annotations:
      testgrid-dashboards: presubmits-kops
      testgrid-tab-name: e2e-podutils
  - name: pull-kops-e2e-kubernetes-aws-1-15-podutils
    branches:
    - master
    optional: true
    labels:
      preset-service-account: "true"
      preset-aws-ssh: "true"
      preset-aws-credential: "true"
      preset-dind-enabled: "true"
      preset-e2e-platform-aws: "true"
    decorate: true
    decoration_config:
      timeout: 90m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200107-164c5e8-experimental
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --aws
        - --aws-cluster-domain=test-cncf-aws.k8s.io
        - --check-leaked-resources=false
        - --cluster=
        - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release-dev/ci/latest-1.15.txt
        - --extract=ci/latest-1.15
        - --ginkgo-parallel
        - --kops-build
        - --provider=aws
        - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort
        - --timeout=55m
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"
    annotations:
      testgrid-dashboards: presubmits-kops
      testgrid-tab-name: e2e-1-15-podutils
  - name: pull-kops-e2e-kubernetes-aws-1-16-podutils
    branches:
    - master
    optional: true
    labels:
      preset-service-account: "true"
      preset-aws-ssh: "true"
      preset-aws-credential: "true"
      preset-dind-enabled: "true"
      preset-e2e-platform-aws: "true"
    decorate: true
    decoration_config:
      timeout: 90m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200107-164c5e8-experimental
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --aws
        - --aws-cluster-domain=test-cncf-aws.k8s.io
        - --check-leaked-resources=false
        - --cluster=
        - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release-dev/ci/latest-1.16.txt
        - --extract=ci/latest-1.16
        - --ginkgo-parallel
        - --kops-build
        - --provider=aws
        - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort|In-tree.*Volumes.*\[Driver:.*aws\]
        - --timeout=55m
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"
    annotations:
      testgrid-dashboards: presubmits-kops
      testgrid-tab-name: e2e-1-16-podutils
  - name: pull-kops-e2e-kubernetes-aws-1-17-podutils
    branches:
    - master
    optional: true
    labels:
      preset-service-account: "true"
      preset-aws-ssh: "true"
      preset-aws-credential: "true"
      preset-dind-enabled: "true"
      preset-e2e-platform-aws: "true"
    decorate: true
    decoration_config:
      timeout: 90m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200107-164c5e8-experimental
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --aws
        - --aws-cluster-domain=test-cncf-aws.k8s.io
        - --check-leaked-resources=false
        - --cluster=
        - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release-dev/ci/latest-1.17.txt
        - --extract=ci/latest-1.17
        - --ginkgo-parallel
        - --kops-build
        - --provider=aws
        - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort
        - --timeout=55m
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"
    annotations:
      testgrid-dashboards: presubmits-kops
      testgrid-tab-name: e2e-1-17-podutils
