# sigs.k8s.io/kwok presubmits
presubmits:
  kubernetes-sigs/kwok:
  - name: pull-kwok-verify-main
    decorate: true
    path_alias: sigs.k8s.io/kwok
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kwok-verify-main
    branches:
    - ^main$
    always_run: true
    spec:
      containers:
      - image: golang:1.17.11
        command:
        - make
        args:
        - verify
  - name: pull-kwok-build-main
    decorate: true
    path_alias: sigs.k8s.io/kwok
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kwok-build-main
    branches:
    - ^main$
    always_run: true
    spec:
      containers:
      - image: golang:1.17.11
        command:
        - make
        args:
        - build
  - name: pull-kwok-unit-test-main
    decorate: true
    path_alias: sigs.k8s.io/kwok
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kwok-unit-test-main
    branches:
    - ^main$
    always_run: true
    spec:
      containers:
      - image: golang:1.17.11
        command:
        - make
        args:
        - unit-test
  - name: pull-kwok-integration-test-main
    decorate: true
    path_alias: sigs.k8s.io/kwok
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kwok-integration-test-main
    branches:
    - ^main$
    always_run: true
    spec:
      containers:
      - image: golang:1.17.11
        command:
        - make
        args:
        - integration-test
  - name: pull-kwok-e2e-test-main
    decorate: true
    path_alias: sigs.k8s.io/kwok
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kwok-e2e-test-main
    branches:
    - ^main$
    always_run: true
    spec:
      containers:
      - image: golang:1.17.11
        command:
        - make
        args:
        - e2e-test
