presets:
- labels:
    preset-azure-secrets-store-creds: "true"
  env:
  - name: AZURE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: azure-secrets-store-cred
        key: clientid
  - name: AZURE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: azure-secrets-store-cred
        key: clientsecret
  - name: TENANT_ID
    valueFrom:
      secretKeyRef:
        name: azure-secrets-store-cred
        key: tenantid
- labels:
    preset-gcp-secrets-store-creds: "true"
  env:
  - name: GCP_SA_JSON
    valueFrom:
      secretKeyRef:
        name: gcp-secrets-store-cred
        key: key.json
