apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: queue-health-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: queue-health-dev
    spec:
      containers:
      - name: grapher
        image: gcr.io/google-containers/queue-health-graph
      - name: poller
        image: gcr.io/google-containers/queue-health-poll
