presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-azure-disk-windows
    decorate: true
    always_run: false
    optional: true
    run_if_changed: 'azure.*\.go'
    path_alias: k8s.io/kubernetes
    branches:
    - release-1.16
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-azure-windows: "true"
      preset-k8s-ssh: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: chewong # TODO(chewong): Change to kubernetes-sigs
      repo: azuredisk-csi-driver
      base_ref: windows-e2e # TODO(chewong): Change to master
      path_alias: sigs.k8s.io/azuredisk-csi-driver
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200318-50fa606-1.16
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --build=quick
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --deployment=aksengine
        - --provider=skeleton
        - --aksengine-admin-username=azureuser
        - --aksengine-admin-password=AdminPassw0rd
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
        - --aksengine-public-key=$(K8S_SSH_PUBLIC_KEY_PATH)
        - --aksengine-private-key=$(K8S_SSH_PRIVATE_KEY_PATH)
        - --aksengine-winZipBuildScript=$(WIN_BUILD)
        - --aksengine-orchestratorRelease=1.16
        - --aksengine-template-url=https://raw.githubusercontent.com/chewong/windows-testing/windows-storage-api-model/job-templates/kubernetes_storage.json # TODO(chewong): Change chewong to kubernetes-sigs
        - --aksengine-win-binaries
        - --aksengine-deploy-custom-k8s
        - --aksengine-agentpoolcount=2
        # Specific test args
        - --test-azure-disk-csi-driver
        - --ginkgo-parallel=1
        - --timeout=420m
        securityContext:
          privileged: true
        env:
        - name: K8S_SSH_PUBLIC_KEY_PATH
          value: /etc/ssh-key-secret/ssh-public # from preset-k8s-ssh label
        - name: K8S_SSH_PRIVATE_KEY_PATH
          value: /etc/ssh-key-secret/ssh-private # from preset-k8s-ssh lable
        - name: AZURE_STORAGE_DRIVER
          value: kubernetes.io/azure-disk # In-tree Azure disk storage class
        - name: TEST_WINDOWS
          value: "true"
  - name: pull-kubernetes-e2e-azure-file-windows
    decorate: true
    always_run: false
    optional: true
    run_if_changed: 'azure.*\.go'
    path_alias: k8s.io/kubernetes
    branches:
    - release-1.16
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-azure-windows: "true"
      preset-k8s-ssh: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: chewong # TODO(chewong): Change to kubernetes-sigs
      repo: azurefile-csi-driver
      base_ref: windows-e2e # TODO(chewong): Change to master
      path_alias: sigs.k8s.io/azurefile-csi-driver
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200318-50fa606-1.16
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --build=quick
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --deployment=aksengine
        - --provider=skeleton
        - --aksengine-admin-username=azureuser
        - --aksengine-admin-password=AdminPassw0rd
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
        - --aksengine-public-key=$(K8S_SSH_PUBLIC_KEY_PATH)
        - --aksengine-private-key=$(K8S_SSH_PRIVATE_KEY_PATH)
        - --aksengine-winZipBuildScript=$(WIN_BUILD)
        - --aksengine-orchestratorRelease=1.16
        - --aksengine-template-url=https://raw.githubusercontent.com/chewong/windows-testing/windows-storage-api-model/job-templates/kubernetes_storage.json # TODO(chewong): Change chewong to kubernetes-sigs
        - --aksengine-win-binaries
        - --aksengine-deploy-custom-k8s
        - --aksengine-agentpoolcount=2
        # Specific test args
        - --test-azure-file-csi-driver
        - --ginkgo-parallel=1
        - --timeout=420m
        securityContext:
          privileged: true
        env:
        - name: K8S_SSH_PUBLIC_KEY_PATH
          value: /etc/ssh-key-secret/ssh-public # from preset-k8s-ssh label
        - name: K8S_SSH_PRIVATE_KEY_PATH
          value: /etc/ssh-key-secret/ssh-private # from preset-k8s-ssh lable
        - name: AZURE_STORAGE_DRIVER
          value: kubernetes.io/azure-file # In-tree Azure file storage class
        - name: TEST_WINDOWS
          value: "true"
