presets:
- labels:
    preset-capz-windows-common-124: "true"
  env:
  - name: "KUBERNETES_VERSION"
    value: "latest-1.24"
  - name: E2E_ARGS
    value: "-kubetest.use-ci-artifacts"
  - name: WINDOWS
    value: "true"
  - name: AZURE_NODE_MACHINE_TYPE
    value: "Standard_D4s_v3"
periodics:
- name: ci-kubernetes-e2e-capz-master-containerd-windows-1-24
  interval: 3h
  decorate: true
  decoration_config:
    timeout: 4h0m0s
  labels:
    preset-azure-cred-only: "true"
    preset-capz-containerd-latest: "true"
    preset-capz-windows-2019: "true"
    preset-capz-windows-common-124: "true"
    preset-capz-windows-parallel: "true"
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - base_ref: main
    org: kubernetes-sigs
    path_alias: sigs.k8s.io/cluster-api-provider-azure
    repo: cluster-api-provider-azure
  spec:
    containers:
    - command:
      - runner.sh
      - ./scripts/ci-conformance.sh
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220428-de61deb68b-1.24
      name: ""
      resources:
        requests:
          cpu: "2"
          memory: 9Gi
      securityContext:
        privileged: true
  annotations:
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    testgrid-dashboards: sig-release-1.24-informing, sig-windows-1.24-release, sig-windows-signal
    testgrid-tab-name: capz-windows-containerd-1.24
- name: ci-kubernetes-e2e-capz-master-containerd-windows-serial-slow-1-24
  interval: 24h
  decorate: true
  decoration_config:
    timeout: 4h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred-only: "true"
    preset-capz-windows-common-124: "true"
    preset-capz-windows-2019: "true"
    preset-capz-containerd-latest: "true"
    preset-capz-serial-slow: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-azure
    base_ref: main
    path_alias: sigs.k8s.io/cluster-api-provider-azure
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220428-de61deb68b-master
        command:
          - "runner.sh"
          - "./scripts/ci-conformance.sh"
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 2
            memory: "9Gi"
  annotations:
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    testgrid-dashboards: sig-windows-1.24-release
    testgrid-tab-name: capz-windows-containerd-serial-slow-1.24
