presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-azure-disk-windows
    decorate: true
    always_run: false
    optional: true
    run_if_changed: 'azure.*\.go'
    path_alias: k8s.io/kubernetes
    branches:
    - release-1.18
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-azure-windows: "true"
      preset-k8s-ssh: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: chewong # TODO(chewong): Change to kubernetes-sigs
      repo: azuredisk-csi-driver
      base_ref: windows-e2e # TODO(chewong): Change to master
      path_alias: sigs.k8s.io/azuredisk-csi-driver
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200322-3d5100e-1.18
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --build=quick
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --deployment=aksengine
        - --provider=skeleton
        - --aksengine-admin-username=azureuser
        - --aksengine-admin-password=AdminPassw0rd
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
        - --aksengine-public-key=$(K8S_SSH_PUBLIC_KEY_PATH)
        - --aksengine-private-key=$(K8S_SSH_PRIVATE_KEY_PATH)
        - --aksengine-winZipBuildScript=$(WIN_BUILD)
        - --aksengine-orchestratorRelease=1.18
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/windows-testing/master/job-templates/kubernetes_storage.json
        - --aksengine-win-binaries
        - --aksengine-deploy-custom-k8s
        - --aksengine-agentpoolcount=2
        # Specific test args
        - --test-azure-disk-csi-driver
        - --ginkgo-parallel=1
        - --timeout=420m
        securityContext:
          privileged: true
        env:
        - name: K8S_SSH_PUBLIC_KEY_PATH
          value: /etc/ssh-key-secret/ssh-public # from preset-k8s-ssh label
        - name: K8S_SSH_PRIVATE_KEY_PATH
          value: /etc/ssh-key-secret/ssh-private # from preset-k8s-ssh label
        - name: AZURE_STORAGE_DRIVER
          value: kubernetes.io/azure-disk # In-tree Azure disk storage class
        - name: TEST_WINDOWS
          value: "true"
  - name: pull-kubernetes-e2e-azure-file-windows
    decorate: true
    always_run: false
    optional: true
    run_if_changed: 'azure.*\.go'
    path_alias: k8s.io/kubernetes
    branches:
    - release-1.18
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-azure-windows: "true"
      preset-k8s-ssh: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: chewong # TODO(chewong): Change to kubernetes-sigs
      repo: azurefile-csi-driver
      base_ref: windows-e2e # TODO(chewong): Change to master
      path_alias: sigs.k8s.io/azurefile-csi-driver
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200322-3d5100e-1.18
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --build=quick
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --deployment=aksengine
        - --provider=skeleton
        - --aksengine-admin-username=azureuser
        - --aksengine-admin-password=AdminPassw0rd
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
        - --aksengine-public-key=$(K8S_SSH_PUBLIC_KEY_PATH)
        - --aksengine-private-key=$(K8S_SSH_PRIVATE_KEY_PATH)
        - --aksengine-winZipBuildScript=$(WIN_BUILD)
        - --aksengine-orchestratorRelease=1.18
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/windows-testing/master/job-templates/kubernetes_storage.json
        - --aksengine-win-binaries
        - --aksengine-deploy-custom-k8s
        - --aksengine-agentpoolcount=2
        # Specific test args
        - --test-azure-file-csi-driver
        - --ginkgo-parallel=1
        - --timeout=420m
        securityContext:
          privileged: true
        env:
        - name: K8S_SSH_PUBLIC_KEY_PATH
          value: /etc/ssh-key-secret/ssh-public # from preset-k8s-ssh label
        - name: K8S_SSH_PRIVATE_KEY_PATH
          value: /etc/ssh-key-secret/ssh-private # from preset-k8s-ssh label
        - name: AZURE_STORAGE_DRIVER
          value: kubernetes.io/azure-file # In-tree Azure file storage class
        - name: TEST_WINDOWS
          value: "true"
periodics:
- interval: 4h
  name: ci-kubernetes-e2e-azure-disk-windows-1-18
  decorate: true
  decoration_config:
    timeout: 2h
  labels:
    preset-service-account: "true"
    preset-azure-cred: "true"
    preset-azure-windows: "true"
    preset-k8s-ssh: "true"
    preset-dind-enabled: "true"
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.18
    path_alias: k8s.io/kubernetes
    workdir: true
  - org: chewong # TODO(chewong): Change to kubernetes-sigs
    repo: azuredisk-csi-driver
    base_ref: windows-e2e # TODO(chewong): Change to master
    path_alias: sigs.k8s.io/azuredisk-csi-driver
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200322-3d5100e-1.18
      command:
      - runner.sh
      - kubetest
      args:
      # Generic e2e test args
      - --test
      - --up
      - --down
      - --build=quick
      - --dump=$(ARTIFACTS)
      # Azure-specific test args
      - --deployment=aksengine
      - --provider=skeleton
      - --aksengine-admin-username=azureuser
      - --aksengine-admin-password=AdminPassw0rd
      - --aksengine-creds=$(AZURE_CREDENTIALS)
      - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.48.0/aks-engine-v0.48.0-linux-amd64.tar.gz
      - --aksengine-public-key=$(K8S_SSH_PUBLIC_KEY_PATH)
      - --aksengine-private-key=$(K8S_SSH_PRIVATE_KEY_PATH)
      - --aksengine-winZipBuildScript=$(WIN_BUILD)
      - --aksengine-orchestratorRelease=1.18
      - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/windows-testing/master/job-templates/kubernetes_storage.json
      - --aksengine-win-binaries
      - --aksengine-deploy-custom-k8s
      - --aksengine-agentpoolcount=2
      # Specific test args
      - --test-azure-disk-csi-driver
      securityContext:
        privileged: true
      env:
      - name: K8S_SSH_PUBLIC_KEY_PATH
        value: /etc/ssh-key-secret/ssh-public # from preset-k8s-ssh label
      - name: K8S_SSH_PRIVATE_KEY_PATH
        value: /etc/ssh-key-secret/ssh-private # from preset-k8s-ssh label
      - name: AZURE_STORAGE_DRIVER
        value: kubernetes.io/azure-disk # In-tree Azure disk storage class
      - name: TEST_WINDOWS
        value: "true"
  annotations:
    testgrid-dashboards: sig-windows, sig-release-1.18-informing, provider-azure-periodic, provider-azure-windows
    testgrid-tab-name: aks-engine-azure-1-18-windows-azure-disk
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: Run Azure Disk e2e test with Azure Disk in-tree volume plugin in a Windows cluster.
- interval: 4h
  name: ci-kubernetes-e2e-azure-file-windows-1-18
  decorate: true
  decoration_config:
    timeout: 2h
  labels:
    preset-service-account: "true"
    preset-azure-cred: "true"
    preset-azure-windows: "true"
    preset-k8s-ssh: "true"
    preset-dind-enabled: "true"
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.18
    path_alias: k8s.io/kubernetes
    workdir: true
  - org: chewong # TODO(chewong): Change to kubernetes-sigs
    repo: azurefile-csi-driver
    base_ref: windows-e2e # TODO(chewong): Change to master
    path_alias: sigs.k8s.io/azurefile-csi-driver
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200322-3d5100e-1.18
      command:
      - runner.sh
      - kubetest
      args:
      # Generic e2e test args
      - --test
      - --up
      - --down
      - --build=quick
      - --dump=$(ARTIFACTS)
      # Azure-specific test args
      - --deployment=aksengine
      - --provider=skeleton
      - --aksengine-admin-username=azureuser
      - --aksengine-admin-password=AdminPassw0rd
      - --aksengine-creds=$(AZURE_CREDENTIALS)
      - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.48.0/aks-engine-v0.48.0-linux-amd64.tar.gz
      - --aksengine-public-key=$(K8S_SSH_PUBLIC_KEY_PATH)
      - --aksengine-private-key=$(K8S_SSH_PRIVATE_KEY_PATH)
      - --aksengine-winZipBuildScript=$(WIN_BUILD)
      - --aksengine-orchestratorRelease=1.18
      - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/windows-testing/master/job-templates/kubernetes_storage.json
      - --aksengine-win-binaries
      - --aksengine-deploy-custom-k8s
      - --aksengine-agentpoolcount=2
      # Specific test args
      - --test-azure-file-csi-driver
      securityContext:
        privileged: true
      env:
      - name: K8S_SSH_PUBLIC_KEY_PATH
        value: /etc/ssh-key-secret/ssh-public # from preset-k8s-ssh label
      - name: K8S_SSH_PRIVATE_KEY_PATH
        value: /etc/ssh-key-secret/ssh-private # from preset-k8s-ssh label
      - name: AZURE_STORAGE_DRIVER
        value: kubernetes.io/azure-file # In-tree Azure file storage class
      - name: TEST_WINDOWS
        value: "true"
  annotations:
    testgrid-dashboards: sig-windows, sig-release-1.18-informing, provider-azure-periodic, provider-azure-windows
    testgrid-tab-name: aks-engine-azure-1-18-windows-azure-file
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: Run Azure File e2e test with Azure File in-tree volume plugin in a Windows cluster.
