presubmits:
  kubernetes-sigs/azuredisk-csi-driver:
  - name: pull-azuredisk-csi-driver-verify
    always_run: true
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200203-25ff2bb-master
        args:
        - "--job=$(JOB_NAME)"
        - "--root=/go/src"
        - "--service-account=/etc/service-account/service-account.json"
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--scenario=execute"
        - --
        - make
        - verify
    annotations:
      testgrid-dashboards: provider-azure-azuredisk-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-azuredisk-csi-driver-verify
      description: "Run code verification tests for Azure Disk CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-azuredisk-csi-driver-unit
    always_run: true
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200203-25ff2bb-master
        args:
        - "--job=$(JOB_NAME)"
        - "--root=/go/src"
        - "--service-account=/etc/service-account/service-account.json"
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--scenario=execute"
        - --
        - make
        - unit-test
    annotations:
      testgrid-dashboards: provider-azure-azuredisk-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-azuredisk-csi-driver-unit
      description: "Run unit tests for Azure Disk CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-azuredisk-csi-driver-sanity
    always_run: true
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200203-25ff2bb-master
        args:
        - "--job=$(JOB_NAME)"
        - "--root=/go/src"
        - "--service-account=/etc/service-account/service-account.json"
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--scenario=execute"
        - --
        - make
        - sanity-test
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-azuredisk-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-azuredisk-csi-driver-sanity
      description: "Run sanity tests for Azure Disk CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-azuredisk-csi-driver-integration
    always_run: true
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200203-25ff2bb-master
        args:
        - "--job=$(JOB_NAME)"
        - "--root=/go/src"
        - "--service-account=/etc/service-account/service-account.json"
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--scenario=execute"
        - --
        - make
        - integration-test
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-azuredisk-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-azuredisk-csi-driver-integration
      description: "Run integration tests for Azure Disk CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-azuredisk-csi-driver-e2e-single-az
    always_run: true
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200203-25ff2bb-master
        args:
        - "--job=$(JOB_NAME)"
        - "--root=/go/src"
        - "--service-account=/etc/service-account/service-account.json"
        - "--repo=k8s.io/kubernetes"
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--scenario=kubernetes_e2e"
        - "--timeout=450"
        - --
        - "--gce-ssh="
        - "--test=true"
        - "--up=true"
        - "--down=true"
        - "--deployment=aksengine"
        - "--build=host-go"
        - "--provider=skeleton"
        - "--ginkgo-parallel=1"
        - "--aksengine-admin-username=azureuser"
        - "--aksengine-creds=$AZURE_CREDENTIALS"
        - "--aksengine-orchestratorRelease=1.16"
        - "--aksengine-location=westus2"
        - "--aksengine-public-key=$AZURE_SSH_PUBLIC_KEY_FILE"
        - "--aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/test/e2e/manifest/single-az.json"
        - "--aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.46.0/aks-engine-v0.46.0-linux-amd64.tar.gz"
        - "--test-azure-disk-csi-driver=True"
        - "--timeout=420m"
        securityContext:
          privileged: true
        env:
          - name: ENABLE_TOPOLOGY
            value: "false"
    annotations:
      testgrid-dashboards: provider-azure-azuredisk-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-azuredisk-csi-driver-e2e-single-az
      description: "Run E2E tests on a single-az cluster for Azure Disk CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-azuredisk-csi-driver-e2e-multi-az
    always_run: true
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200203-25ff2bb-master
        args:
        - "--job=$(JOB_NAME)"
        - "--root=/go/src"
        - "--service-account=/etc/service-account/service-account.json"
        - "--repo=k8s.io/kubernetes"
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--scenario=kubernetes_e2e"
        - "--timeout=450"
        - --
        - "--gce-ssh="
        - "--test=true"
        - "--up=true"
        - "--down=true"
        - "--deployment=aksengine"
        - "--build=host-go"
        - "--provider=skeleton"
        - "--ginkgo-parallel=1"
        - "--aksengine-admin-username=azureuser"
        - "--aksengine-creds=$AZURE_CREDENTIALS"
        - "--aksengine-orchestratorRelease=1.16"
        - "--aksengine-location=eastus2"
        - "--aksengine-public-key=$AZURE_SSH_PUBLIC_KEY_FILE"
        - "--aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/test/e2e/manifest/multi-az.json"
        - "--aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.46.0/aks-engine-v0.46.0-linux-amd64.tar.gz"
        - "--test-azure-disk-csi-driver=True"
        - "--timeout=420m"
        securityContext:
          privileged: true
        env:
          - name: ENABLE_TOPOLOGY
            value: "true"
    annotations:
      testgrid-dashboards: provider-azure-azuredisk-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-azuredisk-csi-driver-e2e-multi-az
      description: "Run E2E tests on a multi-az cluster for Azure Disk CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-in-tree-azure-disk-e2e
    always_run: false
    optional: true
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200203-25ff2bb-master
        args:
        - "--job=$(JOB_NAME)"
        - "--root=/go/src"
        - "--service-account=/etc/service-account/service-account.json"
        - "--repo=k8s.io/kubernetes"
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--scenario=kubernetes_e2e"
        - "--timeout=450"
        - --
        - "--gce-ssh="
        - "--test=true"
        - "--up=true"
        - "--down=true"
        - "--deployment=aksengine"
        - "--build=quick"
        - "--provider=skeleton"
        - "--ginkgo-parallel=1"
        - "--aksengine-admin-username=azureuser"
        - "--aksengine-creds=$AZURE_CREDENTIALS"
        - "--aksengine-orchestratorRelease=1.18"
        - "--aksengine-deploy-custom-k8s=True"
        - "--aksengine-location=westus2"
        - "--aksengine-public-key=$AZURE_SSH_PUBLIC_KEY_FILE"
        - "--aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/test/e2e/manifest/in-tree.json"
        - "--aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.46.0/aks-engine-v0.46.0-linux-amd64.tar.gz"
        - "--test-azure-disk-csi-driver=True"
        - "--timeout=420m"
        securityContext:
          privileged: true
        env:
          - name: AZURE_STORAGE_DRIVER
            value: "kubernetes.io/azure-disk" # In-tree Azure disk storage class
    annotations:
      testgrid-dashboards: provider-azure-azuredisk-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-in-tree-azure-disk-e2e
      description: "Run Azure Disk e2e test with Azure Disk in-tree volume plugin."
      testgrid-num-columns-recent: '30'
  - name: pull-in-tree-azure-disk-e2e-vmss
    always_run: false
    optional: true
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200203-25ff2bb-master
        args:
        - "--job=$(JOB_NAME)"
        - "--root=/go/src"
        - "--service-account=/etc/service-account/service-account.json"
        - "--repo=k8s.io/kubernetes"
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--scenario=kubernetes_e2e"
        - "--timeout=450"
        - --
        - "--gce-ssh="
        - "--test=true"
        - "--up=true"
        - "--down=true"
        - "--deployment=aksengine"
        - "--build=quick"
        - "--provider=skeleton"
        - "--ginkgo-parallel=1"
        - "--aksengine-admin-username=azureuser"
        - "--aksengine-creds=$AZURE_CREDENTIALS"
        - "--aksengine-orchestratorRelease=1.18"
        - "--aksengine-deploy-custom-k8s=True"
        - "--aksengine-location=westus2"
        - "--aksengine-public-key=$AZURE_SSH_PUBLIC_KEY_FILE"
        - "--aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/test/e2e/manifest/in-tree-vmss.json"
        - "--aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.46.0/aks-engine-v0.46.0-linux-amd64.tar.gz"
        - "--test-azure-disk-csi-driver=True"
        - "--timeout=420m"
        securityContext:
          privileged: true
        env:
          - name: AZURE_STORAGE_DRIVER
            value: "kubernetes.io/azure-disk" # In-tree Azure disk storage class
    annotations:
      testgrid-dashboards: provider-azure-azuredisk-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-in-tree-azure-disk-e2e-vmss
      description: "Run Azure Disk e2e test on a VMSS-based cluster with Azure Disk in-tree volume plugin."
      testgrid-num-columns-recent: '30'
  - name: pull-azuredisk-csi-driver-windows-build
    always_run: true
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200203-25ff2bb-master
        args:
        - "--job=$(JOB_NAME)"
        - "--root=/go/src"
        - "--service-account=/etc/service-account/service-account.json"
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--scenario=execute"
        - --
        - make
        - azuredisk-windows
    annotations:
      testgrid-dashboards: provider-azure-azuredisk-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-azuredisk-csi-driver-windows-build
      description: "Run make azuredisk-windows for Azure Disk CSI driver."
      testgrid-num-columns-recent: '30'
