presubmits:
  kubernetes/k8s.io:
  - name: pull-k8sio-groups-test
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: wg-k8s-infra-k8sio
    decorate: true
    path_alias: k8s.io/k8s.io
    run_if_changed: "^groups/"
    branches:
    - ^main$
    spec:
      containers:
      - image: golang:1.13
        command:
        - bash
        args:
        - -c
        - "cd groups && go test"
        env:
        - name: GO111MODULE
          value: "on"
  - name: pull-k8sio-yamllint
    annotations:
      testgrid-dashboards: wg-k8s-infra-k8sio
      testgrid-tab-name: pull-k8sio-yamllint
    always_run: true
    decorate: true
    spec:
      containers:
      - image: quay.io/kubermatic/yamllint:0.1
        command:
        - yamllint
        - -c
        - hack/.yamllint.conf
        - .
