apiVersion: extensions/v1beta1
kind: CronJob
metadata:
  name: issue-creator
spec:
  schedule: "* 5 * * *" # Every day at 5am
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: issue-creator
            image: gcr.io/k8s-testimages/issue-creator:0.1
            args:
            - --token-file=/etc/github-token/token
            - --dry-run=true
            volumeMounts:
            - mountPath: /etc/github-token
              name: token-volume
          volumes:
          - name: token-volume
            secret:
              secretName: issue-creator-github-token
          restartPolicy: OnFailure