# k8s.io/system-validators presubmits
presubmits:
  kubernetes/system-validators:
  - name: pull-system-validators-verify
    path_alias: "k8s.io/system-validators"
    always_run: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20210402-0a23031-master
        command:
        - "./hack/verify-all.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-system-validators
      testgrid-tab-name: pr-verify
