dashboard_groups:
- name: sig-windows
  dashboard_names:
    - sig-windows-signal
    - sig-windows-releases
    - sig-windows-sac
    - sig-windows-containerd
    - sig-windows-presubmit
    - sig-windows-gce
    - sig-windows-azure
    - sig-windows-networking

dashboards:
- name: sig-windows-signal
- name: sig-windows-releases
- name: sig-windows-sac
- name: sig-windows-containerd
- name: sig-windows-presubmit
- name: sig-windows-gce
- name: sig-windows-azure
- name: sig-windows-networking
  dashboard_tab:
  - name: ltsc2019-docker-flannel-winbridge-dsr-disabled-master
    description: Runs Windows (LTSC 2019 with Docker) E2E tests on master branch K8s clusters (with WinDSR disabled) and latest Flannel CNI release in l2bridge network mode.
    test_group_name: ci-kubernetes-e2e-winbridge-docker-dsr-disabled-master-windows
  - name: ltsc2019-docker-flannel-winoverlay-dsr-disabled-master
    description: Runs Windows (LTSC 2019 with Docker) E2E tests on master branch K8s clusters (with WinDSR disabled) and latest Flannel CNI release in overlay network mode.
    test_group_name: ci-kubernetes-e2e-winoverlay-docker-dsr-disabled-master-windows
  - name: ltsc2019-docker-flannel-winbridge-master
    description: Runs Windows (LTSC 2019 with Docker) E2E tests on master branch K8s clusters and latest Flannel CNI release in l2bridge network mode.
    test_group_name: ci-kubernetes-e2e-flannel-l2bridge-master-windows
  - name: ltsc2019-docker-flannel-winoverlay-master
    description: Runs Windows (LTSC 2019 with Docker) E2E tests on master branch K8s clusters and latest Flannel CNI release in overlay network mode.
    test_group_name: ci-kubernetes-e2e-flannel-overlay-master-windows
  - name: ltsc2019-containerd-flannel-sdnbridge-master
    description: Runs Windows (LTSC 2019 with Containerd) E2E tests on master branch K8s clusters and latest Flannel CNI release in l2bridge network mode.
    test_group_name: ci-kubernetes-e2e-sdnbridge-ctrd-master-windows
  - name: ltsc2019-containerd-flannel-sdnoverlay-master
    description: Runs Windows (LTSC 2019 with Containerd) E2E tests on master branch K8s clusters and latest Flannel CNI release in overlay network mode.
    test_group_name: ci-kubernetes-e2e-sdnoverlay-ctrd-master-windows
  - name: ltsc2019-containerd-flannel-sdnbridge-stable
    description: Runs Windows (LTSC 2019 with Containerd) E2E tests on stable branch K8s clusters and latest Flannel CNI release in l2bridge network mode.
    test_group_name: ci-kubernetes-e2e-sdnbridge-ctrd-stable-windows
  - name: ltsc2019-containerd-flannel-sdnoverlay-stable
    description: Runs Windows (LTSC 2019 with Containerd) E2E tests on stable branch K8s clusters and latest Flannel CNI release in overlay network mode.
    test_group_name: ci-kubernetes-e2e-sdnoverlay-ctrd-stable-windows
  - name: sac1909-containerd-flannel-sdnbridge-stable
    description: Runs Windows (SAC 1909 with Containerd) E2E tests on stable branch K8s clusters and latest Flannel CNI release in l2bridge network mode.
    test_group_name: containerd-windows-sac1909-sdnbridge
  - name: sac1909-containerd-flannel-sdnoverlay-stable
    description: Runs Windows (SAC 1909 with Containerd) E2E tests on stable branch K8s clusters and latest Flannel CNI release in overlay network mode.
    test_group_name: containerd-windows-sac1909-sdnoverlay
  - name: sac2004-containerd-flannel-sdnbridge-stable
    description: Runs Windows (SAC 2004 with Containerd) E2E tests on stable branch K8s clusters and latest Flannel CNI release in l2bridge network mode.
    test_group_name: containerd-windows-sac2004-sdnbridge
  - name: sac2004-containerd-flannel-sdnoverlay-stable
    description: Runs Windows (SAC 2004 with Containerd) E2E tests on stable branch K8s clusters and latest Flannel CNI release in overlay network mode.
    test_group_name: containerd-windows-sac2004-sdnoverlay

test_groups:
# Flannel CNI on Windows test groups
- name: ci-kubernetes-e2e-winbridge-docker-dsr-disabled-master-windows
  gcs_prefix: k8s-ovn/logs/ci-kubernetes-e2e-winbridge-docker-dsr-disabled-master-windows
- name: ci-kubernetes-e2e-winoverlay-docker-dsr-disabled-master-windows
  gcs_prefix: k8s-ovn/logs/ci-kubernetes-e2e-winoverlay-docker-dsr-disabled-master-windows
- name: ci-kubernetes-e2e-flannel-l2bridge-master-windows
  gcs_prefix: k8s-ovn/logs/ci-kubernetes-e2e-flannel-l2bridge-master-windows
- name: ci-kubernetes-e2e-flannel-overlay-master-windows
  gcs_prefix: k8s-ovn/logs/ci-kubernetes-e2e-flannel-overlay-master-windows
- name: ci-kubernetes-e2e-sdnbridge-ctrd-master-windows
  gcs_prefix: k8s-ovn/logs/ci-kubernetes-e2e-sdnbridge-ctrd-master-windows
- name: ci-kubernetes-e2e-sdnoverlay-ctrd-master-windows
  gcs_prefix: k8s-ovn/logs/ci-kubernetes-e2e-sdnoverlay-ctrd-master-windows
- name: ci-kubernetes-e2e-sdnbridge-ctrd-stable-windows
  gcs_prefix: k8s-ovn/logs/ci-kubernetes-e2e-sdnbridge-ctrd-stable-windows
- name: ci-kubernetes-e2e-sdnoverlay-ctrd-stable-windows
  gcs_prefix: k8s-ovn/logs/ci-kubernetes-e2e-sdnoverlay-ctrd-stable-windows
- name: containerd-windows-sac1909-sdnbridge
  gcs_prefix: k8s-ovn/logs/containerd-windows-sac1909-sdnbridge
- name: containerd-windows-sac1909-sdnoverlay
  gcs_prefix: k8s-ovn/logs/containerd-windows-sac1909-sdnoverlay
- name: containerd-windows-sac2004-sdnbridge
  gcs_prefix: k8s-ovn/logs/containerd-windows-sac2004-sdnbridge
- name: containerd-windows-sac2004-sdnoverlay
  gcs_prefix: k8s-ovn/logs/containerd-windows-sac2004-sdnoverlay
