branches:
  only:
    - master
language: python
python:
    - "2.7"
services:
    - docker
sudo: required
before_install:
    - docker pull gcr.io/google_containers/kubekins-job-builder:5
install:
# Create and move build under the go path
    - mkdir -p $HOME/gopath/src/k8s.io
    - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/k8s.io/test-infra
    - cd $HOME/gopath/src/k8s.io/test-infra
script:
    - ./verify/verify-bazel.sh
    - ./jenkins/diff-job-config-patch.sh
    - ./jenkins/diff-e2e-runner.sh
    - ./testgrid/jenkins_verify/verify.sh
