branches:
  only:
    - master
language: python
cache:
    directories:
        - node_modules
        - .cache/pip
python:
    - "2.7"
env:
    - GAE_ZIP=google_appengine_1.9.40.zip GAE_ROOT=${HOME}/google_appengine
cache: pip
services:
    - docker
sudo: required
before_install:
    - docker pull gcr.io/google_containers/kubekins-job-builder:5
install:
# Create and move build under the go path
    - mkdir -p $HOME/gopath/src/k8s.io
    - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/k8s.io/test-infra
    - cd $HOME/gopath/src/k8s.io/test-infra
# Based on https://github.com/travis-ci/travis-ci/issues/738#issuecomment-11179888
    - wget -nv https://storage.googleapis.com/appengine-sdks/featured/${GAE_ZIP}
    - unzip -q ${GAE_ZIP} -d ${HOME}
    - pip install -r gubernator/test_requirements.txt
    - npm install mocha
script:
    - ./verify/verify-boilerplate.py
    - ./verify/verify-bazel.sh
    - pylint jenkins/bootstrap.py  # TODO(fejta): all python files
    - pylint queue-health/graph/graph.py  # TODO(fejta): all python files
    - pylint queue-health/weekly_commit_stats.py  # TODO(fejta): all python files
    - ./jenkins/diff-job-config-patch.sh
    - ./jenkins/diff-e2e-runner.sh
    - make -C gcsweb test
    - cd gubernator
    - ./test.sh --nologcapture
    - ./lint.sh
    - ../node_modules/.bin/mocha static/build_test.js
    - cd ..
    - chmod +x testgrid/jenkins_verify/verify.sh
    - ./testgrid/jenkins_verify/verify.sh
