language: python
python:
    - "2.7"
services:
    - docker
before_install:
    - docker pull gcr.io/google_containers/kubekins-job-builder:2
script:
    - python -m unittest discover -s jenkins/test-history -p "*_test.py"
    - ./jenkins/diff-job-config-patch.sh
