language: python
cache: pip
python:
    - "2.7"
services:
    - docker
before_install:
    - docker pull gcr.io/google_containers/kubekins-job-builder:3
install:
    - pip install -r jenkins/test-history/requirements.txt
script:
    - python -m unittest discover -s jenkins/test-history -p "*_test.py"
    - ./jenkins/diff-job-config-patch.sh
