apiVersion: v1
kind: Pod
metadata:
  name: mungegithub
  namespace: default
  labels:
    app: mungegithub
    track: alpha
    version: "0.9.alpha"
spec:
  containers:
  - command:
    - /mungegithub
    - --token-file=/etc/secret-volume/token
    image: gcr.io/google_containers/mungegithub:0.9.alpha
    imagePullPolicy: Always
    name: mungegithub
    ports:
    - name: status
      containerPort: 8080
    resources:
      limits:
        cpu: 100m
    volumeMounts:
    - mountPath: /etc/secret-volume
      name: secret-volume
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
  volumes:
  - name: secret-volume
    secret:
      secretName: github-token
