apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: mungegithub
    track: alpha
    version: "2015-11-16-ef20af4"
  name: mungegithub-2015-11-16-ef20af4
  namespace: default
spec:
  replicas: 1
  selector:
    app: mungegithub
    track: alpha
    version: "2015-11-16-ef20af4"
  template:
    metadata:
      name: mungegithub
      namespace: default
      labels:
        app: mungegithub
        track: alpha
        version: "2015-11-16-ef20af4"
    spec:
      containers:
      - command:
        - /mungegithub
        - --token-file=/etc/secret-volume/token
        image: gcr.io/google_containers/mungegithub:2015-11-16-ef20af4
        imagePullPolicy: IfNotPresent
        name: mungegithub
        ports:
        - name: status
          containerPort: 8080
        resources:
          limits:
            cpu: 100m
        volumeMounts:
        - mountPath: /etc/secret-volume
          name: secret-volume
      dnsPolicy: ClusterFirst
      volumes:
      - name: secret-volume
        secret:
          secretName: github-token
