apiVersion: v1
kind: Service
metadata:
  name: submit-queue-status
  labels:
    app: submit-queue
spec:
  selector:
    app: submit-queue
  ports:
  - name: status
    port: 80
    targetPort: status
  type: LoadBalancer
