presubmits:
  tensorflow/minigo:
  - name: pull-tf-minigo-cc
    always_run: true
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/minigo-testing/minigo-prow-harness-v2:latest
        imagePullPolicy: Always
        args:
        - "--job=$(JOB_NAME)"
        - "--repo=github.com/tensorflow/minigo=$(PULL_REFS)"
        - --service-account=/etc/service-account/service-account.json
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --scenario=execute
        - --
        # Copy prebuilt tensorflow into repo.
        - .testing/setup.sh
        - && 
        # Check clang-format, test with board_size 9 and 19.
        - ./cc/test.sh

  - name: tf-minigo-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/minigo-testing/minigo-prow-harness-v2:latest
        imagePullPolicy: Always
        args:
        - "--job=$(JOB_NAME)"
        - "--repo=github.com/tensorflow/minigo=$(PULL_REFS)"
        - --service-account=/etc/service-account/service-account.json
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --scenario=execute
        - --
        - ./test.sh

postsubmits:
  tensorflow/minigo:
  - name: tf-minigo-postsubmit
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/minigo-testing/minigo-prow-harness-v2:latest
        imagePullPolicy: Always
        args:
        - "--job=$(JOB_NAME)"
        - "--repo=github.com/tensorflow/minigo=$(PULL_REFS)"
        - --service-account=/etc/service-account/service-account.json
        - --upload=gs://kubernetes-jenkins/logs
        - --scenario=execute
        - --
        - ./test.sh

periodics:
- name: tf-minigo-periodic
  interval: 8h
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/minigo-testing/minigo-prow-harness-v2:latest
      imagePullPolicy: Always
      args:
      - "--job=$(JOB_NAME)"
      - --repo=github.com/tensorflow/minigo=master
      - --service-account=/etc/service-account/service-account.json
      - --upload=gs://kubernetes-jenkins/logs
      - --scenario=execute
      - --
      - ./test.sh
