periodics:  
- interval: 4h
  name: cluster-api-provider-aws-test-creds
  always_run: true
  decorate: true
  labels:
    preset-service-account: "true"
    preset-aws-credential: "true"
  path_alias: "sigs.k8s.io/cluster-api-provider-aws"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/cluster-api:v20180720-d52d72975      
      args:
      - "--repo=sigs.k8s.io/cluster-api-provider-aws"
      - "--root=/go/src"
      - "--upload=gs://kubernetes-jenkins/logs"
      - "--scenario=execute"
      - "--"
      - "./scripts/ci-aws-cred-test.sh"