apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: token-counter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: token-counter
    spec:
      containers:
      - name: token-counter
        args:
        - --stderrthreshold=0
        - --influx-host=http://influxdb-kubernetes:8086
        - --influx-password=$(INFLUXDB_ROOT_PWD)
        - --token=/github-tokens/k8s-merge-robot
        - --token=/github-tokens/k8s-ci-robot
        image: gcr.io/google-containers/github-token-counter:v20160922-130312
        env:
        - name: INFLUXDB_ROOT_PWD
          valueFrom:
            secretKeyRef:
              name: influxdb-kubernetes
              key: rootpassword
        volumeMounts:
        - mountPath: /github-tokens
          readOnly: true
          name: github-tokens-secret
        - mountPath: /etc/ssl/certs
          name: certificates
      volumes:
      - name: github-tokens-secret
        secret:
          secretName: github-tokens
      - name: certificates
        configMap:
          name: certificates
          items:
          - key: ca-certificates.crt
            path: ca-certificates.crt
