presubmits:
  GoogleCloudPlatform/k8s-multicluster-ingress:
  - name: pull-kubernetes-multicluster-ingress-test
    branches:
    - master
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220428-de61deb68b-master
        args:
        - "--repo=github.com/GoogleCloudPlatform/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - --scenario=execute
        - --
        - make
        - --
        - -j
        - "5"
        - test
        - coveralls
        - vet
        - fmt
        - lint
        volumeMounts:
        - name: coveralls
          mountPath: /etc/coveralls-token
          readOnly: true
      volumes:
      - name: coveralls
        secret:
          secretName: k8s-multicluster-ingress-coveralls-token

postsubmits:
  GoogleCloudPlatform/k8s-multicluster-ingress:
  - name: ci-kubemci-image-push
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220428-de61deb68b-master
        args:
        - "--repo=k8s.io/test-infra=master"
        - "--root=/go/src/"
        - "--timeout=90"
        - --scenario=execute
        - --
        - make
        - --
        - -C
        - images/kubemci
        - push-latest
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true

    annotations:
      testgrid-dashboards: sig-multicluster-kubemci
      testgrid-tab-name: kubemci-image-push
periodics:
- interval: 6h
  name: ci-kubernetes-multicluster-ingress-test
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220428-de61deb68b-master
      args:
      - --repo=github.com/GoogleCloudPlatform/k8s-multicluster-ingress=master
      - --root=/go/src
      - --timeout=50
      - --service-account=/etc/service-account/service-account.json
      - --upload=gs://kubernetes-jenkins/logs
      - --scenario=execute
      - --
      - make
      - --
      - -j
      - "5"
      - test
      - coveralls
      - vet
      - fmt
      - lint
      volumeMounts:
      - name: coveralls
        mountPath: /etc/coveralls-token
        readOnly: true
    volumes:
    - name: coveralls
      secret:
        secretName: k8s-multicluster-ingress-coveralls-token

  annotations:
    testgrid-dashboards: sig-multicluster-kubemci
    testgrid-tab-name: ci-kubemci-unit-tests
