presubmits:
  kubernetes/cloud-provider-alibaba-cloud:
  - name: pull-cloud-provider-alibaba-cloud-check
    always_run: true
    branches:
    - master
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190514-6c3cafa-master
        command:
        - make
        args:
        - check

  - name: pull-cloud-provider-alibaba-cloud-unit-test
    always_run: true
    branches:
    - master
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190514-6c3cafa-master
        command:
        - make
        args:
        - unit-test
