presubmits:
  kubernetes-sigs/image-builder:
  - name: pull-azure-vhds
    labels:
      preset-azure-cred: "true"
    decorate: true
    run_if_changed: 'images/capi/.*'
    decoration_config:
      timeout: 1h
    max_concurrency: 5
    path_alias: sigs.k8s.io/image-builder
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20210403-e49d2c6-master
        args:
          - runner.sh
          - "./images/capi/packer/azure/scripts/ci-azure-e2e.sh"
        resources:
          requests:
            cpu: 1000m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-image-builder
      testgrid-tab-name: pr-azure-vhds
  - name: pull-azure-sigs
    labels:
      preset-azure-cred: "true"
    decorate: true
    always_run: false
    optional: true
    decoration_config:
      timeout: 1h
    max_concurrency: 5
    path_alias: sigs.k8s.io/image-builder
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20210403-e49d2c6-master
        args:
          - runner.sh
          - "./images/capi/packer/azure/scripts/ci-azure-e2e.sh"
        env:
          - name: AZURE_BUILD_FORMAT
            value: "sig"
        resources:
          requests:
            cpu: 1000m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-image-builder
      testgrid-tab-name: pr-azure-sigs
  - name: json-sort-check
    decorate: true
    run_if_changed: 'images/capi/.*\.json$'
    decoration_config:
      timeout: 1h
    max_concurrency: 5
    path_alias: sigs.k8s.io/image-builder
    spec:
      containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20210403-e49d2c6-master
          args:
            - runner.sh
            - "./images/capi/hack/ci-json-sort.sh"
          resources:
            requests:
              cpu: 1000m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-image-builder
      testgrid-tab-name: pr-json-sort-check
  - name: pull-packer-validate
    decorate: true
    run_if_changed: 'images/capi/Makefile|images/capi/packer/.*|images/capi/scripts/ci-packer-validate\.sh'
    decoration_config:
      timeout: 20m
    max_concurrency: 5
    path_alias: sigs.k8s.io/image-builder
    spec:
      containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20210403-e49d2c6-master
          args:
          - runner.sh
          - "./images/capi/scripts/ci-packer-validate.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-image-builder
      testgrid-tab-name: pr-packer-validate
  - name: pull-image-builder-gcp-all
    path_alias: sigs.k8s.io/image-builder
    always_run: false
    optional: true
    decorate: true
    decoration_config:
      timeout: 2h
    max_concurrency: 5
    labels:
      preset-service-account: "true"
    run_if_changed: 'images/capi/.*'
    spec:
      containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20201021-a62ce8a-master
          args:
            - runner.sh
            - "./images/capi/packer/gce/scripts/ci-gce.sh"
          env:
            - name: BOSKOS_HOST
              value: "boskos.test-pods.svc.cluster.local"
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "4Gi"
              cpu: 2000m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-image-builder
      testgrid-tab-name: pr-pull-image-builder-gcp-all
