# sigs.k8s.io/etcdadm presubmits
presubmits:
  kubernetes-sigs/etcdadm:
  - name: pull-etcdadm-verify
    path_alias: "sigs.k8s.io/etcdadm"
    always_run: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20191028-e674b0d-master
        command:
        - "./hack/verify-all.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-etcdadm
      testgrid-tab-name: pr-verify
  - name: pull-etcdadm-test-init
    path_alias: "sigs.k8s.io/etcdadm"
    always_run: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20191028-e674b0d-master
        command:
        - "runner.sh"
        - "./test/e2e/init.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-etcdadm
      testgrid-tab-name: pr-test-init
