postsubmits:
  kubernetes/release:
    - name: post-release-push-image-k8s-ci-builder
      cluster: k8s-infra-prow-build-trusted
      annotations:
        testgrid-dashboards: sig-release-releng-informing, sig-release-image-pushes, wg-k8s-infra-gcb
        testgrid-alert-email: release-managers+alerts@kubernetes.io
      decorate: true
      run_if_changed: '^(cmd\/|compile-release-tools|go.(mod|sum)|images\/releng\/k8s-ci-builder\/|pkg\/)'
      branches:
        - ^master$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20210622-762366a
            command:
              - /run.sh
            args:
              - --project=k8s-staging-releng
              - --scratch-bucket=gs://k8s-staging-releng-gcb
              - --env-passthrough=REGISTRY
              - --build-dir=.
              - images/releng/k8s-ci-builder
            env:
              - name: LOG_TO_STDOUT
                value: "y"
              - name: REGISTRY
                value: "gcr.io/k8s-staging-releng"
      rerun_auth_config:
        github_team_ids:
          - 2241179 # release-managers
    - name: post-release-push-image-k8s-cloud-builder
      cluster: k8s-infra-prow-build-trusted
      annotations:
        testgrid-dashboards: sig-release-releng-informing, sig-release-image-pushes, wg-k8s-infra-gcb
        testgrid-alert-email: release-managers+alerts@kubernetes.io
      decorate: true
      run_if_changed: '^images\/'
      branches:
        - ^master$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20210622-762366a
            command:
              - /run.sh
            args:
              - --project=k8s-staging-releng
              - --scratch-bucket=gs://k8s-staging-releng-gcb
              - --env-passthrough=PULL_BASE_REF,REGISTRY
              - images/k8s-cloud-builder
            env:
              - name: LOG_TO_STDOUT
                value: "y"
              - name: REGISTRY
                value: "gcr.io/k8s-staging-releng"
      rerun_auth_config:
        github_team_ids:
          - 2241179 # release-managers
    - name: post-release-push-image-releng-ci
      cluster: k8s-infra-prow-build-trusted
      annotations:
        testgrid-dashboards: sig-release-releng-informing, sig-release-image-pushes, wg-k8s-infra-gcb
        testgrid-alert-email: release-managers+alerts@kubernetes.io
      decorate: true
      run_if_changed: '^images\/'
      branches:
        - ^master$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20210622-762366a
            command:
              - /run.sh
            args:
              - --project=k8s-staging-releng
              - --scratch-bucket=gs://k8s-staging-releng-gcb
              - --env-passthrough=PULL_BASE_REF,REGISTRY
              - --build-dir=.
              - images/releng/ci
            env:
              - name: LOG_TO_STDOUT
                value: "y"
              - name: REGISTRY
                value: "gcr.io/k8s-staging-releng"
      rerun_auth_config:
        github_team_ids:
          - 2241179 # release-managers
    - name: post-release-push-image-kubepkg
      cluster: k8s-infra-prow-build-trusted
      annotations:
        testgrid-dashboards: sig-release-releng-informing, sig-release-image-pushes, wg-k8s-infra-gcb
        testgrid-alert-email: release-managers+alerts@kubernetes.io
      decorate: true
      branches:
        - ^master$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20210622-762366a
            command:
              - /run.sh
            args:
              - --project=k8s-staging-releng
              - --scratch-bucket=gs://k8s-staging-releng-gcb
              - --env-passthrough=PULL_BASE_REF,REGISTRY
              - --gcb-config=./cloudbuild-kubepkg.yaml
              - .
            env:
              - name: LOG_TO_STDOUT
                value: "y"
              - name: REGISTRY
                value: "gcr.io/k8s-staging-releng"
        rerun_auth_config:
          github_team_ids:
            - 2241179 # release-managers
