presubmits:
  kubernetes-sigs/service-apis:
  - name: pull-service-apis-build
    annotations:
      testgrid-dashboards: sig-network-service-apis
      testgrid-tab-name: build
    decorate: true
    path_alias: sigs.k8s.io/service-apis
    always_run: true
    skip_report: false
    spec:
      containers:
      - image: golang:1.13
        command:
        - make
