presubmits:
  kubernetes/cloud-provider-openstack:
  - name: openstack-cloud-controller-manager-e2e-test
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    path_alias: "k8s.io/cloud-provider-openstack"
    always_run: false
    branches:
      - ^master$
    run_if_changed: '^(pkg\/openstack\/|cmd\/openstack-cloud-controller-manager\/|tests\/e2e\/cloudprovider\/)'
    optional: false
    decorate: true
    decoration_config:
      timeout: 3h
    spec:
      containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20210808-1eaeec7-master
          env:
          - name: "BOSKOS_HOST"
            value: "boskos.test-pods.svc.cluster.local"
          command:
          - "runner.sh"
          - "./tests/ci-occm-e2e.sh"
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
    annotations:
      testgrid-dashboards: provider-openstack-openstack-cloud-controller-manager
      testgrid-tab-name: presubmit-e2e-test
