presubmits:
  kubernetes-sigs/controller-runtime:
  - name: pull-controller-runtime-test
    decorate: true
    optional: true
    path_alias: sigs.k8s.io/controller-runtime
    spec:
      containers:
      - image: golang:1.12
        command:
        - ./hack/ci-check-everything.sh
        resources:
          requests:
            cpu: 4000m
    annotations:
      testgrid-dashboards: sig-api-machinery-kubebuilder
      testgrid-tab-name: controller-runtime
