periodics:
- interval: 6h
  name: periodic-controller-runtime-test-master
  decorate: true
  extra_refs:
  - org: kubernetes-sigs
    repo: controller-runtime
    base_ref: master
  spec:
    containers:
    - image: golang:1.13
      command:
      - ./hack/ci-check-everything.sh
      resources:
        requests:
          cpu: 6000m
  annotations:
    testgrid-dashboards: sig-api-machinery-kubebuilder
    testgrid-tab-name: controller-runtime-periodic-master
