presubmits:
  kubernetes-sigs/aws-iam-authenticator:
  - name: pull-aws-iam-authenticator-unit
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20210825-f1955d1-master
        command:
        - runner.sh
        args:
        - make
        - test
    annotations:
      testgrid-dashboards: provider-aws-iam-authenticator
      testgrid-tab-name: pull-unit-test
      description: AWS IAM Authenticator unit test on pull request
      testgrid-num-columns-recent: '30'
