# sigs.k8s.io/cluster-api-provider-docker presubmits
presubmits:
  kubernetes-sigs/cluster-api-provider-docker:
  - name: pull-cluster-api-provider-docker-verify
    path_alias: "sigs.k8s.io/cluster-api-provider-docker"
    always_run: true
    optional: false
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190703-1f4d616-master
        command:
        - "./hack/verify-all.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-docker
      testgrid-tab-name: pr-verify
