postsubmits:
  # this is the github repo we'll build from; this block needs to be repeated for each repo.
  kubernetes-sigs/cluster-api:
    - name: post-cluster-api-push-images
      cluster: k8s-infra-prow-build-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes
      decorate: true
      branches:
        - ^master$
        - ^release-0.2$
        # this is a regex for semver, from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20210302-aa40187
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-cluster-api
              - --scratch-bucket=gs://k8s-staging-cluster-api-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
  kubernetes-sigs/cluster-api-provider-aws:
    - name: post-cluster-api-provider-aws-push-images
      cluster: k8s-infra-prow-build-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes
      decorate: true
      branches:
        - ^master$
        - ^release-0.4$
        # this is a regex for semver, from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20210302-aa40187
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-cluster-api-aws
              - --scratch-bucket=gs://k8s-staging-cluster-api-aws-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
  kubernetes-sigs/cluster-api-provider-azure:
    - name: post-cluster-api-provider-azure-push-images
      cluster: k8s-infra-prow-build-trusted
      annotations:
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes, sig-cluster-lifecycle-cluster-api-provider-azure
        testgrid-alert-email: k8s-infra-staging-cluster-api-azure@kubernetes.io
      decorate: true
      branches:
        - ^master$
        - ^release-0.3$
        - ^release-0.4$
        # this is a regex for semver, from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20210302-aa40187
            command:
              - /run.sh
            args:
              - --project=k8s-staging-cluster-api-azure
              - --scratch-bucket=gs://k8s-staging-cluster-api-azure-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
  kubernetes-sigs/cluster-api-provider-digitalocean:
    - name: post-cluster-api-provider-digitalocean-push-images
      cluster: k8s-infra-prow-build-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes
        testgrid-alert-email: k8s-infra-staging-cluster-api-do@kubernetes.io
      decorate: true
      branches:
        - ^master$
        - ^release-0.3$
        # this is a regex for semver, from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20210302-aa40187
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-cluster-api-do
              - --scratch-bucket=gs://k8s-staging-cluster-api-do-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
  kubernetes-sigs/cluster-api-provider-gcp:
    - name: post-cluster-api-provider-gcp-push-images
      cluster: k8s-infra-prow-build-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes
      decorate: true
      branches:
        - ^master$
        - ^release-.*
        # this is a regex for semver, from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20210302-aa40187
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-cluster-api-gcp
              - --scratch-bucket=gs://k8s-staging-cluster-api-gcp-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
  kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm:
    - name: post-cluster-api-bootstrap-provider-push-images
      cluster: k8s-infra-prow-build-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes
      decorate: true
      branches:
        - ^master$
        # this is a regex for semver, from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20210302-aa40187
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-capi-kubeadm
              - --scratch-bucket=gs://k8s-staging-capi-kubeadm-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
  kubernetes-sigs/cluster-api-provider-openstack:
    - name: post-cluster-api-provider-openstack-push-images
      cluster: k8s-infra-prow-build-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes
      decorate: true
      branches:
        - ^master$
        - ^release-.+$
        # this is a regex for semver, from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20210302-aa40187
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-capi-openstack
              - --scratch-bucket=gs://k8s-staging-capi-openstack-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
  kubernetes-sigs/image-builder:
    - name: post-image-builder-push-images
      cluster: k8s-infra-prow-build-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes
      decorate: true
      branches:
        - ^master$
        # this is a regex for semver, from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20210302-aa40187
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-scl-image-builder
              - --scratch-bucket=gs://k8s-staging-scl-image-builder-gcb
              - --env-passthrough=PULL_BASE_REF
              - --with-git-dir
              - .

periodics:
- name: cluster-api-push-images-nightly
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  cron: '0 8 * * *' # everyday at 0:00 PT (8:00 UTC)
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api
      base_ref: master
      path_alias: sigs.k8s.io/cluster-api
  spec:
    serviceAccountName: gcb-builder
    containers:
      - image: gcr.io/k8s-testimages/image-builder:v20210302-aa40187
        command:
          - /run.sh
        args:
          # this is the project GCB will run in, which is the same as the GCR images are pushed to.
          - --project=k8s-staging-cluster-api
          - --scratch-bucket=gs://k8s-staging-cluster-api-gcb
          - --env-passthrough=PULL_BASE_REF
          - --gcb-config=cloudbuild-nightly.yaml
          - .
        env:
        # We need to emulate a pull job for the cloud build to work the same
        # way as it usually does.
        - name: PULL_BASE_REF
          value: master
  annotations:
    # this is the name of some testgrid dashboard to report to.
    testgrid-dashboards: sig-cluster-lifecycle-image-pushes
    testgrid-tab-name: cluster-api-push-images-nightly
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
- name: cluster-api-provider-openstack-push-images-nightly
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  cron: '0 8 * * *' # everyday at 0:00 PT (8:00 UTC)
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-openstack
      base_ref: master
      path_alias: sigs.k8s.io/cluster-api-provider-openstack
  spec:
    serviceAccountName: gcb-builder
    containers:
      - image: gcr.io/k8s-testimages/image-builder:v20210302-aa40187
        command:
          - /run.sh
        args:
          # this is the project GCB will run in, which is the same as the GCR images are pushed to.
          - --project=k8s-staging-capi-openstack
          - --scratch-bucket=gs://k8s-staging-capi-openstack-gcb
          - --env-passthrough=PULL_BASE_REF
          - --gcb-config=cloudbuild-nightly.yaml
          - .
        env:
        # We need to emulate a pull job for the cloud build to work the same
        # way as it usually does.
        - name: PULL_BASE_REF
          value: master
  annotations:
    # this is the name of some testgrid dashboard to report to.
    testgrid-dashboards: sig-cluster-lifecycle-image-pushes
    testgrid-tab-name: cluster-api-provider-openstack-push-images-nightly
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io

##
## This Job is a temporary solution that builds the machine images using image-builder repository
## and packer. this is not the image for CAPG manager.
## This should be replaced in the future with the work from https://github.com/kubernetes-sigs/image-builder/pull/445
##
- name: cluster-api-provider-gcp-build-image-nightly
  cluster: k8s-infra-prow-build-trusted
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-service-account: "true"
  decorate: true
  decoration_config:
    timeout: 3h
  # TODO(dims): switch to cron after we get this job working.
  interval: 2h
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-gcp
      base_ref: master
      path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
    - org: kubernetes-sigs
      repo: image-builder
      base_ref: master
      path_alias: "sigs.k8s.io/image-builder"
  spec:
    serviceAccountName: gcb-builder
    containers:
      - image: gcr.io/k8s-testimages/image-builder:v20210302-aa40187
        env:
          # TODO(dims): reuse this project for now to test this job.
          # need to create a separate project.
          - name: "GCP_PROJECT"
            value: "k8s-staging-cloud-provider-gcp"
          - name: "SKIP_CLEANUP"
            value: "true"
        command:
          - /home/prow/go/src/sigs.k8s.io/cluster-api-provider-gcp/scripts/ci-e2e.sh
        args:
          - "--verbose"
          - "--build-image-only"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9000Mi"
            # during the tests more like 3-20m is used
            cpu: 2000m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-image-pushes
    testgrid-tab-name: capg-build-image-nightly
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "2"
