postsubmits:
  # this is the github repo we'll build from; this block needs to be repeated for each repo.
  kubernetes-sigs/cluster-api:
    - name: post-cluster-api-push-images
      cluster: test-infra-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes
      decorate: true
      branches:
        - ^master$
      spec:
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20190906-d5d7ce3
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-cluster-api
              - --scratch-bucket=gs://k8s-staging-cluster-api-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: /creds/service-account.json
            volumeMounts:
              - name: creds
                mountPath: /creds
        volumes:
          - name: creds
            secret:
              secretName: deployer-service-account
  kubernetes-sigs/cluster-api-provider-aws:
    - name: post-cluster-api-provider-aws-push-images
      cluster: test-infra-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes
      decorate: true
      branches:
        - ^master$
      spec:
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20190906-d5d7ce3
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-cluster-api-aws
              - --scratch-bucket=gs://k8s-staging-cluster-api-aws-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: /creds/service-account.json
            volumeMounts:
              - name: creds
                mountPath: /creds
        volumes:
          - name: creds
            secret:
              secretName: deployer-service-account
  kubernetes-sigs/cluster-api-provider-gcp:
    - name: post-cluster-api-provider-gcp-push-images
      cluster: test-infra-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes
      decorate: true
      branches:
        - ^master$
      spec:
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20190906-d5d7ce3
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-cluster-api-gcp
              - --scratch-bucket=gs://k8s-staging-cluster-api-gcp-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: /creds/service-account.json
            volumeMounts:
              - name: creds
                mountPath: /creds
        volumes:
          - name: creds
            secret:
              secretName: deployer-service-account
