postsubmits:
  cncf/apisnoop:
    - name: apisnoop-push-auditlogger-images
      cluster: test-infra-trusted
      annotations:
        testgrid-dashboards: conformance-apisnoop
        testgrid-tab-name: apisnoop-auditlogger-image
        testgrid-alert-email: apisnoop@ii.coop
        description: Builds the auditlogger image for APISnoop deployments
      decorate: true
      branches:
        - ^master$
      spec:
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20200205-602500d
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-apisnoop
              - --scratch-bucket=gs://k8s-staging-apisnoop-gcb
              - --env-passthrough=PULL_BASE_REF
              - apps/auditlogger/
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: /creds/service-account.json
            volumeMounts:
              - name: creds
                mountPath: /creds
        volumes:
          - name: creds
            secret:
              secretName: deployer-service-account
    - name: apisnoop-push-postgres-images
      cluster: test-infra-trusted
      annotations:
        testgrid-dashboards: conformance-apisnoop
        testgrid-tab-name: apisnoop-postgres-image
        testgrid-alert-email: apisnoop@ii.coop
        description: Builds the postgres image for APISnoop deployments
      decorate: true
      branches:
        - ^master$
      spec:
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20200205-602500d
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-apisnoop
              - --scratch-bucket=gs://k8s-staging-apisnoop-gcb
              - --env-passthrough=PULL_BASE_REF
              - apps/postgres/
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: /creds/service-account.json
            volumeMounts:
              - name: creds
                mountPath: /creds
        volumes:
          - name: creds
            secret:
              secretName: deployer-service-account
    - name: apisnoop-push-hasura-images
      cluster: test-infra-trusted
      annotations:
        testgrid-dashboards: conformance-apisnoop
        testgrid-tab-name: apisnoop-hasura-image
        testgrid-alert-email: apisnoop@ii.coop
        description: Builds the hasura image for APISnoop deployments
      decorate: true
      branches:
        - ^master$
      spec:
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20200205-602500d
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-apisnoop
              - --scratch-bucket=gs://k8s-staging-apisnoop-gcb
              - --env-passthrough=PULL_BASE_REF
              - apps/hasura/
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: /creds/service-account.json
            volumeMounts:
              - name: creds
                mountPath: /creds
        volumes:
          - name: creds
            secret:
              secretName: deployer-service-account
