postsubmits:
  kubernetes-sigs/seccomp-operator:
    - name: post-seccomp-operator-push-image
      cluster: k8s-infra-prow-build-trusted
      decorate: true
      always_run: true
      branches:
        - ^master$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20200731-7f46eab
            command:
              - /run.sh
            args:
              - --project=k8s-infra-staging-seccomp-operator
              - --scratch-bucket=gs://k8s-infra-staging-seccomp-operator
              - .
            env:
              - name: LOG_TO_STDOUT
                value: "y"
