apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        command:
        image: grafana/grafana:3.1.1
        ports:
        - name: grafana-port
          containerPort: 3000
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: database-volume
        env:
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana
                key: rootpassword
      volumes:
      - name: database-volume
        persistentVolumeClaim:
          claimName: grafana-database-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-service
  namespace: default
spec:
  ports:
  - name: grafana
    port: 3000
    targetPort: grafana-port
  selector:
    app: grafana
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: grafana-stack
  name: grafana-database
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: grafana-database
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-database-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
