presubmits:
  kubernetes-sigs/kubebuilder-declarative-pattern:
  - name: pull-declarative-test
    decorate: true
    path_alias: sigs.k8s.io/kubebuilder-declarative-pattern
    always_run: true
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20201111-a263fd7-master
        command:
        - "./hack/ci/test.sh"
