apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        command:
        image: grafana/grafana:3.1.1
        ports:
        - name: grafana-port
          containerPort: 3000
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: database-volume
        env:
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana
                key: rootpassword
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_USERS_ALLOW_SIGN_UP
            value: "false"
          - name: GF_USERS_ALLOW_ORG_CREATE
            value: "false"
      volumes:
      - name: database-volume
        persistentVolumeClaim:
          claimName: grafana-database-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-service
spec:
  ports:
  - name: grafana
    port: 3000
    targetPort: grafana-port
  selector:
    app: grafana
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-database-claim
  annotations:
    volume.alpha.kubernetes.io/storage-class: value
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
