periodics:
# GCE upgrades
- interval: 2h
  name: ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/k8s-beta
      - --extract=ci/k8s-stable1
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:ClusterUpgrade\] --upgrade-target=ci/k8s-beta --upgrade-image=gci
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210715-521d667-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-1.13-1.14-upgrade-cluster

- interval: 2h
  name: ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster-parallel
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/k8s-beta
      - --extract=ci/k8s-stable1
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:ClusterUpgrade\] --upgrade-target=ci/k8s-beta --upgrade-image=gci
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210715-521d667-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-1.13-1.14-upgrade-cluster-parallel

- interval: 2h
  name: ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster-new
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/k8s-beta
      - --extract=ci/k8s-stable1
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\]
      - --skew
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:ClusterUpgrade\] --upgrade-target=ci/k8s-beta --upgrade-image=gci
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210715-521d667-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-1.13-1.14-upgrade-cluster-new

- interval: 2h
  name: ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster-new-parallel
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/k8s-beta
      - --extract=ci/k8s-stable1
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]
      - --skew
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:ClusterUpgrade\] --upgrade-target=ci/k8s-beta --upgrade-image=gci
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210715-521d667-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-1.13-1.14-upgrade-cluster-new-parallel

- interval: 2h
  name: ci-kubernetes-e2e-gce-stable1-beta-upgrade-master
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/k8s-beta
      - --extract=ci/k8s-stable1
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:MasterUpgrade\] --upgrade-target=ci/k8s-beta
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210715-521d667-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-1.13-1.14-upgrade-master

- interval: 2h
  name: ci-kubernetes-e2e-gce-stable1-beta-upgrade-master-parallel
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/k8s-beta
      - --extract=ci/k8s-stable1
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:MasterUpgrade\] --upgrade-target=ci/k8s-beta
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210715-521d667-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-1.13-1.14-upgrade-master-parallel

- interval: 12h
  name: ci-kubernetes-e2e-gce-stable2-stable1-upgrade-cluster
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/k8s-stable1
      - --extract=ci/k8s-stable2
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:ClusterUpgrade\] --upgrade-target=ci/k8s-stable1 --upgrade-image=gci
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210715-521d667-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-1.12-1.13-upgrade-cluster

- interval: 12h
  name: ci-kubernetes-e2e-gce-stable2-stable1-upgrade-cluster-new
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/k8s-stable1
      - --extract=ci/k8s-stable2
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --skew
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:ClusterUpgrade\] --upgrade-target=ci/k8s-stable1 --upgrade-image=gci
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210715-521d667-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-1.12-1.13-upgrade-cluster-new

- interval: 12h
  name: ci-kubernetes-e2e-gce-stable2-stable1-upgrade-master
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/k8s-stable1
      - --extract=ci/k8s-stable2
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:MasterUpgrade\] --upgrade-target=ci/k8s-stable1
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210715-521d667-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-1.12-1.13-upgrade-master
