periodics:
- name: ci-cluster-api-provider-gcp-build
  interval: 1h
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/gcloud-in-go:v20190125-cc5d6ecff3
      args:
      - "--repo=sigs.k8s.io/cluster-api-provider-gcp"
      - "--root=/go/src"
      - "--upload=gs://kubernetes-jenkins/logs"
      - "--scenario=execute"
      - "--"
      - "./scripts/ci-build.sh"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
    testgrid-tab-name: build
- name: ci-cluster-api-provider-gcp-test
  interval: 1h
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/cluster-api:v20190114-652973a54
      args:
      - "--repo=sigs.k8s.io/cluster-api-provider-gcp"
      - "--root=/go/src"
      - "--upload=gs://kubernetes-jenkins/logs"
      - "--scenario=execute"
      - "--"
      - "./scripts/ci-test.sh"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
    testgrid-tab-name: unit tests
- name: ci-cluster-api-provider-gcp-make-conformance-master
  interval: 3h
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  spec:
    containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20191009-4f1de38-master
        env:
          - name: "CAPI_BRANCH"
            value: "master"
          - name: "CABPK_BRANCH"
            value: "master"
        args:
          - "--repo=k8s.io/kubernetes=master"
          - "--repo=sigs.k8s.io/cluster-api-provider-gcp=master"
          - "--repo=sigs.k8s.io/cluster-api=master"
          - "--repo=sigs.k8s.io/image-builder=master"
          - "--repo=sigs.k8s.io/kind=master"
          - "--root=/go/src"
          - "--service-account=/etc/service-account/service-account.json"
          - "--upload=gs://kubernetes-jenkins/logs"
          - "--scenario=execute"
          - "--"
          - "bash"
          - "--"
          - "-c"
          - "cd ./../../sigs.k8s.io/cluster-api-provider-gcp && scripts/ci-e2e.sh"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9000Mi"
            # during the tests more like 3-20m is used
            cpu: 2000m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
    testgrid-tab-name: e2e-tests-master
- name: ci-cluster-api-provider-gcp-make-conformance-stable
  interval: 3h
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  spec:
    containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20191009-4f1de38-master
        env:
          - name: "CAPI_BRANCH"
            value: "stable"
          - name: "CABPK_BRANCH"
            value: "stable"
        args:
          - "--repo=k8s.io/kubernetes=master"
          - "--repo=sigs.k8s.io/cluster-api-provider-gcp=master"
          - "--repo=sigs.k8s.io/cluster-api=master"
          - "--repo=sigs.k8s.io/image-builder=master"
          - "--repo=sigs.k8s.io/kind=master"
          - "--root=/go/src"
          - "--service-account=/etc/service-account/service-account.json"
          - "--upload=gs://kubernetes-jenkins/logs"
          - "--scenario=execute"
          - "--"
          - "bash"
          - "--"
          - "-c"
          - "cd ./../../sigs.k8s.io/cluster-api-provider-gcp && scripts/ci-e2e.sh"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9000Mi"
            # during the tests more like 3-20m is used
            cpu: 2000m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
    testgrid-tab-name: e2e-tests-stable
