periodics:
- interval: 1h
  name: ci-kubernetes-e2e-kops-aws-beta
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
    preset-e2e-platform-aws: "true"
  decorate: true
  decoration_config:
    timeout: 140m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --aws
      - --cluster=e2e-kops-aws-beta.test-cncf-aws.k8s.io
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release-dev/ci/k8s-beta.txt
      - --extract=ci/k8s-beta
      - --ginkgo-parallel
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort
      - --timeout=120m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200117-6b79ed4-master
  annotations:
    testgrid-dashboards: google-aws, sig-cluster-lifecycle-kops
    testgrid-tab-name: kops-aws-beta

- interval: 2h
  name: ci-kubernetes-e2e-kops-aws-stable1
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 140m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-stable1.test-cncf-aws.k8s.io
      - --deployment=kops
      - --env=KUBE_SSH_USER=admin
      - --extract=ci/k8s-stable1
      - --ginkgo-parallel
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort
      - --timeout=120m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200117-6b79ed4-master
  annotations:
    testgrid-dashboards: google-aws, sig-cluster-lifecycle-kops
    testgrid-tab-name: kops-aws-stable1

- interval: 4h
  name: ci-kubernetes-e2e-kops-aws-stable2
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 140m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-stable2.test-cncf-aws.k8s.io
      - --deployment=kops
      - --env=KUBE_SSH_USER=admin
      - --extract=ci/k8s-stable2
      - --ginkgo-parallel
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort
      - --timeout=120m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200117-6b79ed4-master
  annotations:
    testgrid-dashboards: google-aws, sig-cluster-lifecycle-kops
    testgrid-tab-name: kops-aws-stable2

- interval: 6h
  name: ci-kubernetes-e2e-kops-aws-stable3
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 140m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-stable3.test-cncf-aws.k8s.io
      - --deployment=kops
      - --env=KUBE_SSH_USER=admin
      - --extract=ci/k8s-stable3
      - --ginkgo-parallel
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort
      - --timeout=120m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200117-6b79ed4-master
  annotations:
    testgrid-dashboards: google-aws, sig-cluster-lifecycle-kops
    testgrid-tab-name: kops-aws-stable3

- interval: 8h
  name: e2e-kops-aws-k8s-1-15
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1.15.test-cncf-aws.k8s.io
      - --deployment=kops
      - --env=KUBE_SSH_USER=admin
      - --extract=release/stable-1.15
      - --ginkgo-parallel
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci.txt
      - --provider=aws
      - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|AdmissionWebhook|Aggregator|CustomResource
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:latest-1.15
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: google-aws, sig-cluster-lifecycle-kops
    testgrid-tab-name: kops-aws-k8s-1.15

- interval: 8h
  name: e2e-kops-aws-k8s-1-14
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1.14.test-cncf-aws.k8s.io
      - --deployment=kops
      - --env=KUBE_SSH_USER=admin
      - --extract=release/stable-1.14
      - --ginkgo-parallel
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci.txt
      - --provider=aws
      - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|AdmissionWebhook|Aggregator|CustomResource
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:latest-1.14
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: google-aws, sig-cluster-lifecycle-kops
    testgrid-tab-name: kops-aws-k8s-1.14

- interval: 8h
  name: e2e-kops-aws-k8s-1-13
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1.13.test-cncf-aws.k8s.io
      - --deployment=kops
      - --env=KUBE_SSH_USER=admin
      - --extract=release/stable-1.13
      - --ginkgo-parallel
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci.txt
      - --provider=aws
      - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|AdmissionWebhook|Aggregator|CustomResource|SchedulerPredicates|Lease
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:latest-1.13
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: google-aws, sig-cluster-lifecycle-kops
    testgrid-tab-name: kops-aws-k8s-1.13

- interval: 8h
  name: e2e-kops-aws-k8s-1-12
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1.12.test-cncf-aws.k8s.io
      - --deployment=kops
      - --env=KUBE_SSH_USER=admin
      - --extract=release/stable-1.12
      - --ginkgo-parallel
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci.txt
      - --provider=aws
      - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|AdmissionWebhook|Aggregator|CustomResource|SchedulerPredicates|Lease|hostAliases|NodePort
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:latest-1.12
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: google-aws, sig-cluster-lifecycle-kops
    testgrid-tab-name: kops-aws-k8s-1.12

- interval: 8h
  name: e2e-kops-aws-k8s-1-11
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1.11.test-cncf-aws.k8s.io
      - --deployment=kops
      - --env=KUBE_SSH_USER=admin
      - --extract=release/stable-1.11
      - --ginkgo-parallel
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci.txt
      - --provider=aws
      - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|AdmissionWebhook|Aggregator|CustomResource|SchedulerPredicates|Lease|hostAliases|NodePort
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:latest-1.11
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: google-aws, sig-cluster-lifecycle-kops
    testgrid-tab-name: kops-aws-k8s-1.11

- interval: 8h
  name: e2e-kops-aws-k8s-1-10
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1.10.test-cncf-aws.k8s.io
      - --deployment=kops
      - --env=KUBE_SSH_USER=admin
      - --env=KOPS_RUN_OBSOLETE_VERSION=true
      - --extract=release/stable-1.10
      - --ginkgo-parallel
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci.txt
      - --provider=aws
      - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|AdmissionWebhook|Aggregator|CustomResource|SchedulerPredicates|Lease|hostAliases|NodePort
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:latest-1.10
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: google-aws, sig-cluster-lifecycle-kops
    testgrid-tab-name: kops-aws-k8s-1.10

- interval: 8h
  name: e2e-kops-aws-k8s-1-9
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1.9.test-cncf-aws.k8s.io
      - --deployment=kops
      - --env=KUBE_SSH_USER=admin
      - --env=KOPS_RUN_OBSOLETE_VERSION=true
      - --extract=release/stable-1.9
      - --ginkgo-parallel
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci.txt
      - --provider=aws
      - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|AdmissionWebhook|Aggregator|CustomResource|SchedulerPredicates|Lease|hostAliases|NodePort
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:latest-1.10
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: google-aws, sig-cluster-lifecycle-kops
    testgrid-tab-name: kops-aws-k8s-1.9
