# periodic jobs

periodics:
- name: ci-kubernetes-e2e-kubeadm-kinder-external-etcd-master
  interval: 2h
  decorate: true
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  decoration_config:
    timeout: 40m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  - org: kubernetes
    repo: kubeadm
    base_ref: master
    path_alias: k8s.io/kubeadm
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190612-e8a5406-master
      command:
      - runner.sh
      - "../kubeadm/kinder/ci/kinder-run.sh"
      args:
      - "external-etcd-master"
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "9000Mi"
          cpu: 2000m
- name: ci-kubernetes-e2e-kubeadm-kinder-external-etcd-1-14
  interval: 12h
  decorate: true
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  decoration_config:
    timeout: 40m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.14
    path_alias: k8s.io/kubernetes
  - org: kubernetes
    repo: kubeadm
    base_ref: master
    path_alias: k8s.io/kubeadm
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190612-e8a5406-1.14
      command:
      - runner.sh
      - "../kubeadm/kinder/ci/kinder-run.sh"
      args:
      - "external-etcd-1.14"
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "9000Mi"
          cpu: 2000m
