# periodic jobs

periodics:
- name: ci-kubernetes-e2e-kubeadm-kinder-kustomize-master
  interval: 2h
  decorate: true
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kubeadm
    testgrid-tab-name: kubeadm-kinder-kustomize-master
    testgrid-alert-email: kubernetes-sig-cluster-lifecycle@googlegroups.com
    description: "OWNER: sig-cluster-lifecycle (kinder); Uses kubeadm/kinder to create a cluster with kustomizations on static pod manifests"
    testgrid-num-columns-recent: "20"
    testgrid-num-failures-to-alert: "4"
    testgrid-alert-stale-results-hours: "8"
  decoration_config:
    timeout: 40m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  - org: kubernetes
    repo: kubeadm
    base_ref: master
    path_alias: k8s.io/kubeadm
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20191002-1ea0701-master
      command:
      - runner.sh
      - "../kubeadm/kinder/ci/kinder-run.sh"
      args:
      - "kustomize-master"
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "9000Mi"
          cpu: 2000m
