presets:
- labels:
    preset-minikube-e2e-creds: "true"
  env:
  - name: GCS_CREDS
    value: /root/.config/gcloud/k8s-minikube-build-gcs.json
  volumes:
  - name: k8s-minikube-build-gcs
    secret:
      secretName: k8s-minikube-build-gcs
  - name: ssh-key-secret
    secret:
      secretName: ssh-key-secret
  volumeMounts:
  - name: k8s-minikube-build-gcs
    mountPath: /root/.config/gcloud
    readOnly: true
  - name: ssh-key-secret
    mountPath: /root/.ssh
    readOnly: true

presubmits:
  kubernetes/minikube:
  - name: pull-minikube-linux-kvm
    labels:
        preset-minikube-e2e-creds: "true"
    always_run: false
    optional: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-minikube/minikube-e2e:v20181022-a850455f-experimental
        command:
        - make
        args:
        - "test-linux-kvm"
