periodics:
- name: sig-auth-serviceaccount-admission-controller-migration
  annotations:
    testgrid-dashboards: sig-auth-gce
    testgrid-tab-name: upgrade-tests
    # TODO: use sig-auth mailing list
    testgrid-alert-email: zshihang@google.com
    testgrid-num-failures-to-alert: "3"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  decorate: true
  # TODO: lower to once a day
  interval: 2h
  spec:
    containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20201014-882eb3f-master
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --check-leaked-resources
        - --check-version-skew=false
        # TODO: change to release/stable-x.y
        - --extract=ci/latest
        - --extract=ci/latest-1.19
        - --gcp-node-image=gci
        - --gcp-zone=us-west1-b
        - --provider=gce
        - --upgrade_args="--ginkgo.focus=\[Feature:BoundServiceAccountTokenVolume\] --upgrade-target=ci/latest --upgrade-image=gci"
        - --timeout=60m
        env:
        - name: STORAGE_MEDIA_TYPE
          value: "application/vnd.kubernetes.protobuf"
