presubmits:
  kubernetes-csi/csi-driver-host-path:
  - name: pull-sig-storage-csi-driver-host-path-kubernetes-1-13
    always_run: true
    decorate: true
    skip_report: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      # We need this image because it has Docker in Docker and go
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190301-76bc03340-master
        command:
        - runner.sh
        args:
        - /bin/sh
        - -c
        # Not all branches have Prow support.
        - if [ -e .prow.sh ]; then ./.prow.sh; fi
        env:
        - name: CSI_PROW_KUBERNETES_VERSION
          value: "1.13.3"
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 2000m
  - name: pull-sig-storage-csi-driver-host-path-kubernetes-master
    always_run: true
    decorate: true
    skip_report: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      # We need this image because it has Docker in Docker and go
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190301-76bc03340-master
        command:
        - runner.sh
        args:
        - /bin/sh
        - -c
        # Not all branches have Prow support.
        - if [ -e .prow.sh ]; then ./.prow.sh; fi
        env:
        - name: CSI_PROW_KUBERNETES_VERSION
          value: "latest"
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
      resources:
        requests:
          # these are both a bit below peak usage during build
          # this is mostly for building kubernetes
          memory: "9000Mi"
          # during the tests more like 3-20m is used
          cpu: 2000m

periodics:
- interval: 6h
  name: ci-kubernetes-csi-stable
  decorate: true
  extra_refs:
  - org: kubernetes-csi
    repo: csi-driver-host-path
    # TODO: replace with master once branch prow is merged
    base_ref: prow
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-kind-volume-mounts: "true"
  spec:
    containers:
    # We need this image because it has Docker in Docker and go
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190301-76bc03340-master
      command:
      - runner.sh
      args:
      - ./.prow.sh
      env:
      - name: CSI_PROW_KUBERNETES_VERSION
        value: "latest"
      - name: CSI_PROW_BUILD_JOB
        value: "false"
      - name: CSI_PROW_DEPLOYMENT
        value: "kubernetes-1.13"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
    resources:
      requests:
        # these are both a bit below peak usage during build
        # this is mostly for building kubernetes
        memory: "9000Mi"
        # during the tests more like 3-20m is used
        cpu: 2000m
