presubmits:
  kubernetes-csi/csi-driver-host-path:
  - name: pull-sig-storage-csi-driver-host-path
    always_run: false
    decorate: true
    skip_report: false
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      # We need this image because it has Docker and kind.
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190220-615bdbe2e-master
        command:
        - runner.sh
        args:
        - ./.prow.sh
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        # Copied from config/jobs/kubernetes/sig-testing/verify.yaml.
        resources:
          requests:
            cpu: 4
