presets:
- labels:
    preset-common-gce-windows: "true"
  env:
  - name: KUBE_GCE_ENABLE_IP_ALIASES
    value: "true"
  - name: KUBERNETES_NODE_PLATFORM
    value: "windows"
  - name: KUBELET_TEST_ARGS
    value: "--feature-gates=KubeletPodResources=false"
  - name: USE_TEST_INFRA_LOG_DUMPING
    value: "true"
- labels:
    preset-e2e-gce-windows: "true"
  env:
  - name: NUM_WINDOWS_NODES
    value: "3"
  - name: NUM_NODES
    value: "2"
- labels:
    preset-e2e-gce-windows-containerd: "true"
  env:
  - name: PREPULL_TIMEOUT
    value: "30m"
  - name: WINDOWS_ENABLE_DSR
    value: "true"
- labels:
    preset-load-gce-windows: "true"
  env:
  - name: MASTER_SIZE
    value: "n1-standard-4"
  - name: NUM_WINDOWS_NODES
    value: "1"
  - name: NUM_NODES
    value: "1"
  - name: NODE_SIZE
    value: "n1-standard-8"
  - name: NODE_DISK_SIZE
    value: "100GB"
  # Ensure good enough architecture for master machines.
  - name: MASTER_MIN_CPU_ARCHITECTURE
    value: "Intel Broadwell"
  - name: MAX_PODS_PER_NODE
    value: "128"
  - name: PREPULL_TIMEOUT
    value: "10m"
  # APIResponsiveness test depends on Prometheus server which couldn't scrape kube-proxy,
  # unless it’s binding 0.0.0.0 as per https://github.com/helm/charts/issues/16476
  # Reference: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-presets.yaml#L127
  - name: KUBEPROXY_TEST_ARGS
    value: "--profiling --metrics-bind-address=0.0.0.0"
  - name: WINDOWS_NODE_OS_DISTRIBUTION
    value: "win2019"
