postsubmits:
  kubernetes/k8s.io:
  - name: post-k8sio-deploy-prow-build-resources
    cluster: k8s-infra-prow-build-trusted
    decorate: true
    max_concurrency: 1
    run_if_changed: "^infra/gcp/clusters/projects/k8s-infra-prow-build/"
    branches:
    - ^main$
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: wg-k8s-infra-k8sio
      testgrid-alert-email: k8s-infra-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
    rerun_auth_config:
      github_team_slugs:
      - org: kubernetes
        slug: wg-k8s-infra-leads
      - org: kubernetes
        slug: test-infra-admins
    spec:
      serviceAccountName: prow-deployer
      containers:
      - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
        command:
        - ./infra/gcp/clusters/projects/k8s-infra-prow-build/deploy.sh
  - name: post-k8sio-deploy-prow-build-trusted-resources
    cluster: k8s-infra-prow-build-trusted
    decorate: true
    max_concurrency: 1
    run_if_changed: "^infra/gcp/clusters/projects/k8s-infra-prow-build-trusted/"
    branches:
    - ^main$
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: wg-k8s-infra-k8sio
      testgrid-alert-email: k8s-infra-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
    rerun_auth_config:
      github_team_slugs:
      - org: kubernetes
        slug: wg-k8s-infra-leads
      - org: kubernetes
        slug: test-infra-admins
    spec:
      serviceAccountName: prow-deployer
      containers:
      - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
        command:
        - ./infra/gcp/clusters/projects/k8s-infra-prow-build-trusted/deploy.sh

