periodics:
- name: ci-k8sio-audit
  # TODO(spiffxp): low interval for debugging / verification, remove and adjust cron when done
  interval: 10m
  # interval: 3h
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  max_concurrency: 1
  extra_refs:
  - org: kubernetes
    repo: k8s.io
    base_ref: main
  annotations:
    testgrid-dashboards: wg-k8s-infra-k8sio
    testgrid-alert-email: k8s-infra-alerts@kubernetes.io
    testgrid-num-failures-to-alert: '1'
  rerun_auth_config:
    github_team_slugs:
    - org: kubernetes
      slug: wg-k8s-infra-leads
    - org: kubernetes
      slug: k8s-infra-gcp-auditors
  spec:
    serviceAccountName: k8s-infra-gcp-auditor
    containers:
    - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
      imagePullPolicy: Always
      command:
      - ./audit/create-or-update-audit-pr.sh
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
    volumes:
    - name: github
      secret:
        secretName: k8s-infra-ci-robot-github-token

- name: ci-k8sio-autobump-prow-build-clusters
  # TODO(spiffxp): low interval for debugging / verification, remove and adjust cron when done
  interval: 10m
  # cron: "30 17-22/5 * * 1-5"  # Run at 10:30 and 15:30 PST (17:05 UTC) Mon-Fri
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  max_concurrency: 1
  extra_refs:
  - org: kubernetes
    repo: k8s.io
    base_ref: main
  annotations:
    testgrid-dashboards: wg-k8s-infra-k8sio
    testgrid-alert-email: k8s-infra-alerts@kubernetes.io
    testgrid-num-failures-to-alert: '1'
    description: runs autobumper to create/update a PR that updates prow build cluster component images
  rerun_auth_config:
    github_team_slugs:
    # proxy for wg-k8s-infra-oncall
    - org: kubernetes
      slug: wg-k8s-infra-leads
    # proxy for test-infra-oncall
    - org: kubernetes
      slug: test-infra-admins
  spec:
    containers:
    - image: gcr.io/k8s-prow/generic-autobumper:v20210727-e0795bc861
      command:
      - /app/prow/cmd/generic-autobumper/app.binary
      args:
      - --config=hack/autobump-config.yaml
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
    volumes:
    - name: github
      secret:
        secretName: oauth-token

postsubmits:
  kubernetes/k8s.io:
  - name: post-k8sio-dns-update
    cluster: k8s-infra-prow-build-trusted
    decorate: true
    max_concurrency: 1
    run_if_changed: "^dns/zone-configs/"
    branches:
    - ^main$
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: wg-k8s-infra-k8sio
      testgrid-alert-email: k8s-infra-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
    rerun_auth_config:
      github_team_slugs:
      - org: kubernetes
        slug: wg-k8s-infra-leads
    spec:
      serviceAccountName: k8s-infra-dns-updater
      containers:
      - image: us.gcr.io/k8s-artifacts-prod/infra-tools/octodns:v20200616-67ce585
        command:
        - bash
        args:
        - -c
        - "cd dns && make push-local"
