periodics:
- name: metrics-bigquery
  cron: "03 0-23/6 * * *"  # like interval: 6h, but explicitly starting at 00:03 UTC
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  max_concurrency: 1
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  annotations:
    testgrid-dashboards: sig-testing-misc, wg-k8s-infra-prow
    testgrid-alert-email: kubernetes-sig-testing-alerts@googlegroups.com, k8s-infra-alerts@kubernetes.io
    testgrid-num-failures-to-alert: '2'
    description: Runs BigQuery queries to generate data for metrics.
  rerun_auth_config:
    github_team_slugs:
    # proxy for wg-k8s-infra-oncall
    - org: kubernetes
      slug: wg-k8s-infra-leads
    # proxy for test-infra-oncall
    - org: kubernetes
      slug: test-infra-admins
  spec:
    serviceAccountName: k8s-metrics
    containers:
    - image: gcr.io/k8s-testimages/bigquery:v20210707-0f9c540
      args:
      - ./metrics/bigquery.py
      - --bucket=gs://k8s-metrics
      - --project=k8s-infra-prow-build-trusted
