dashboard_groups:
- name: sig-gcp
  dashboard_names:
    - sig-gcp-master
    - sig-gcp-release-1.11
    - sig-gcp-release-1.12
    - sig-gcp-compute-persistent-disk-csi-driver

dashboards:
- name: sig-gcp-master
  dashboard_tab:
    - name: gci-gke
      test_group_name: ci-kubernetes-e2e-gci-gke
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gci-gke-serial
      test_group_name: ci-kubernetes-e2e-gci-gke-serial
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gci-gke-slow
      test_group_name: ci-kubernetes-e2e-gci-gke-slow
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gci-gke-alpha-features
      test_group_name: ci-kubernetes-e2e-gci-gke-alpha-features
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gci-gke-alpha-enabled-default
      test_group_name: ci-kubernetes-e2e-gci-gke-alpha-enabled-default
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gci-gke-flaky
      test_group_name: ci-kubernetes-e2e-gci-gke-flaky
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gci-gke-ingress
      test_group_name: ci-kubernetes-e2e-gci-gke-ingress
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gci-gke-multizone
      test_group_name: ci-kubernetes-e2e-gci-gke-multizone
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gci-gke-reboot
      test_group_name: ci-kubernetes-e2e-gci-gke-reboot
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gci-gke-updown
      test_group_name: ci-kubernetes-e2e-gci-gke-updown
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gke-device-plugin-gpu
      test_group_name: ci-kubernetes-e2e-gke-device-plugin-gpu
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gke-device-plugin-gpu-p100
      test_group_name: ci-kubernetes-e2e-gke-device-plugin-gpu-p100
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gke-canary
      test_group_name: ci-kubernetes-e2e-gke-canary
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit

- name: sig-gcp-release-1.11
  dashboard_tab:
    - name: gke-cos-1.13-default
      test_group_name: ci-kubernetes-e2e-gke-cos-k8sstable1-default
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gke-cos-1.13-slow
      test_group_name: ci-kubernetes-e2e-gke-cos-k8sstable1-slow
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gke-cos-1.13-serial
      test_group_name: ci-kubernetes-e2e-gke-cos-k8sstable1-serial
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gke-cos-1.13-ingress
      test_group_name: ci-kubernetes-e2e-gke-cos-k8sstable1-ingress
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gke-cos-1.13-reboot
      test_group_name: ci-kubernetes-e2e-gke-cos-k8sstable1-reboot
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit

- name: sig-gcp-release-1.12
  dashboard_tab:
    - name: gke-cos-1.12-default
      test_group_name: ci-kubernetes-e2e-gke-cos-k8sstable2-default
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gke-cos-1.12-slow
      test_group_name: ci-kubernetes-e2e-gke-cos-k8sstable2-slow
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gke-cos-1.12-serial
      test_group_name: ci-kubernetes-e2e-gke-cos-k8sstable2-serial
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gke-cos-1.12-ingress
      test_group_name: ci-kubernetes-e2e-gke-cos-k8sstable2-ingress
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit
    - name: gke-cos-1.12-reboot
      test_group_name: ci-kubernetes-e2e-gke-cos-k8sstable2-reboot
      column_header:
        - configuration_value: node_os_image
        - configuration_value: Commit
        - configuration_value: infra-commit

- name: sig-gcp-compute-persistent-disk-csi-driver
