periodics:
- name: ci-cluster-api-build
  interval: 1h
  decorate: true
  path_alias: sigs.k8s.io/cluster-api
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190703-1f4d616-master
      command:
      - runner.sh
      - ./scripts/ci-build.sh
- name: ci-cluster-api-test
  interval: 1h
  decorate: true
  path_alias: sigs.k8s.io/cluster-api
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190703-1f4d616-master
      args:
      - runner.sh
      - ./scripts/ci-test.sh
      resources:
        requests:
          cpu: 3
          memory: "6Gi"
