periodics:
- name: ci-cluster-api-build
  interval: 1h
  decorate: true
  labels:
    preset-service-account: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: master
    path_alias: sigs.k8s.io/cluster-api
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200117-6b79ed4-master
      command:
      - "./scripts/ci-build.sh"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api
    testgrid-tab-name: build
    testgrid-alert-email: kubernetes-sig-cluster-lifecycle-cluster-api-alerts@googlegroups.com
    testgrid-num-failures-to-alert: "2"
- name: ci-cluster-api-test
  interval: 1h
  decorate: true
  labels:
    preset-service-account: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: master
    path_alias: sigs.k8s.io/cluster-api
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200117-6b79ed4-master
      command:
      - "./scripts/ci-test.sh"
      resources:
        requests:
          cpu: 3
          memory: "6Gi"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api
    testgrid-tab-name: unit tests
    testgrid-alert-email: kubernetes-sig-cluster-lifecycle-cluster-api-alerts@googlegroups.com
    testgrid-num-failures-to-alert: "2"
- name: ci-cluster-api-e2e-test
  interval: 1h
  decorate: true
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api
      base_ref: master
      path_alias: sigs.k8s.io/cluster-api
  spec:
    containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200117-6b79ed4-master
        args:
          - runner.sh
          - "./scripts/ci-capd-e2e.sh"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "4000m"
            memory: "6Gi"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api
    testgrid-tab-name: e2e tests
    testgrid-alert-email: kubernetes-sig-cluster-lifecycle-cluster-api-alerts@googlegroups.com
    testgrid-num-failures-to-alert: "2"
- name: ci-cluster-api-build-release-0-2
  interval: 1h
  decorate: true
  labels:
    preset-service-account: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-0.2
    path_alias: sigs.k8s.io/cluster-api
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200117-6b79ed4-master
      command:
      - "./scripts/ci-build.sh"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api
    testgrid-tab-name: build-release-0-2
    testgrid-alert-email: kubernetes-sig-cluster-lifecycle-cluster-api-alerts@googlegroups.com
    testgrid-num-failures-to-alert: "2"
- name: ci-cluster-api-test-release-0-2
  interval: 1h
  decorate: true
  labels:
    preset-service-account: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-0.2
    path_alias: sigs.k8s.io/cluster-api
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200117-6b79ed4-master
      command:
      - "./scripts/ci-test.sh"
      resources:
        requests:
          cpu: 3
          memory: "6Gi"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api
    testgrid-tab-name: unit tests-release-0-2
    testgrid-alert-email: kubernetes-sig-cluster-lifecycle-cluster-api-alerts@googlegroups.com
    testgrid-num-failures-to-alert: "2"
