presubmits:
  kubernetes-sigs/cluster-api:
  - name: pull-cluster-api-build
    decorate: true
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    labels:
      preset-service-account: "true"
    skip_branches:
    - gh-pages
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190703-1f4d616-master
        command:
        - runner.sh
        - ./scripts/ci-build.sh
  - name: pull-cluster-api-make
    decorate: true
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    skip_branches:
    - gh-pages
    spec:
      containers:
      - command:
        - runner.sh
        - ./scripts/ci-make.sh
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        image: gcr.io/k8s-testimages/kubekins-e2e:v20190703-1f4d616-master
        resources:
          requests:
            memory: "6Gi"
  - name: pull-cluster-api-test
    decorate: true
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    labels:
      preset-service-account: "true"
    skip_branches:
    - gh-pages
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190703-1f4d616-master
        args:
        - runner.sh
        - ./scripts/ci-test.sh
        resources:
          requests:
            cpu: 3
            memory: "6Gi"
  - name: pull-cluster-api-vendor-in-sync
    decorate: true
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    labels:
      preset-service-account: "true"
    skip_branches:
    - gh-pages
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190703-1f4d616-master
        command:
        - runner.sh
        - ./scripts/ci-is-vendor-in-sync.sh
  - name: pull-cluster-api-integration
    labels:
      preset-dind-enabled: "true"
      preset-service-account: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190703-1f4d616-master
        command:
        - runner.sh
        - ./scripts/ci-integration.sh
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 4
            memory: "6Gi"
