presubmits:
  kubeflow/examples:
  - name: kubeflow-examples-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmits for kubeflow/examples.
  kubeflow/kubeflow:
  - name: kubeflow-presubmit
    always_run: true         # Run for every PR, or only when requested.
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmit tests for Kubeflow.
  kubeflow/pytorch-operator:
  - name: kubeflow-pytorch-operator-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmits for kubeflow/pytorch-operator.
  kubeflow/reporting:
  - name: kubeflow-reporting-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmits for kubeflow/reporting.
  kubeflow/website:
  - name: kubeflow-website-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmits for kubeflow/website.
  kubeflow/testing:
  - name: kubeflow-testing-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmits for kubeflow/testing.
  kubeflow/tf-operator:
  - name: kubeflow-tf-operator-presubmit
    always_run: true         # Run for every PR, or only when requested.
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmits for kubeflow/tf-operator.
  kubeflow/katib:
  - name: kubeflow-katib-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmits for kubeflow/katib.
  kubeflow/experimental-kvc:
  - name: kubeflow-experimental-kvc-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmits for kubeflow/experimental-kvc.
  kubeflow/experimental-seldon:
  - name: kubeflow-experimental-seldon-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmits for kubeflow/experimental-seldon.
  kubeflow/experimental-beagle:
  - name: kubeflow-experimental-beagle-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmits for kubeflow/experimental-beagle.
  kubeflow/caffe2-operator:
  - name: kubeflow-caffe2-operator-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmits for kubeflow/caffe2-operator.
  kubeflow/kubebench:
  - name: kubeflow-kubebench-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmit tests for kubeflow/kubebench.
  kubeflow/mpi-operator:
  - name: kubeflow-mpi-operator-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmit tests for kubeflow/mpi-operator.
  kubeflow/chainer-operator:
  - name: kubeflow-chainer-operator-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmit tests for kubeflow/chainer-operator.
  kubeflow/mxnet-operator:
  - name: kubeflow-mxnet-operator-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmits for kubeflow/mxnet-operator.
  kubeflow/arena:
  - name: kubeflow-arena-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmit tests for kubeflow/arena.
  kubeflow/fairing:
  - name: kubeflow-fairing-presubmit
    always_run: true
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmit tests for kubeflow/fairing.
  kubeflow/metadata:
  - name: kubeflow-metadata-presubmit
    always_run: true
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmit tests for kubeflow/metadata.
  kubeflow/kfserving:
  - name: kubeflow-kfserving-presubmit
    always_run: true
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmits for kubeflow/kfserving.
  kubeflow/manifests:
  - name: kubeflow-manifests-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Presubmits for kubeflow/manifests.
  kubeflow/pipelines:
  - name: kubeflow-pipeline-e2e-test
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190703-1f4d616-master
        command:
        - ./test/presubmit-tests-with-pipeline-deployment.sh
        args:
        - --workflow_file
        - e2e_test_gke_v2.yaml
        - --test_result_folder
        - e2e_test
  - name: kubeflow-pipeline-sample-test
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190703-1f4d616-master
        command:
        - ./test/presubmit-tests-with-pipeline-deployment.sh
        args:
        - --workflow_file
        - sample_test.yaml
        - --test_result_folder
        - sample_test
        - --timeout
        - "3600"
  - name: kubeflow-pipeline-upgrade-test
    always_run: true
    decorate: true
    skip_report: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190703-1f4d616-master
        command:
        - ./test/upgrade-tests.sh
        args:
        - --test_result_folder
        - upgrade_test
#   - name: kubeflow-pipeline-e2e-test-gce-minikube
#     always_run: true
#     decorate: true
#     skip_report: true
#     labels:
#       preset-service-account: "true"
#     spec:
#       containers:
#       - image: gcr.io/k8s-testimages/kubekins-e2e:v20190703-1f4d616-master
#         command:
#         - ./test/presubmit-tests-gce-minikube.sh
#         args:
#         - --workflow_file
#         - e2e_test_gke.yaml
#         - --test_result_folder
#         - e2e_test_gke
