postsubmits:
  kubeflow/examples:
  - name: kubeflow-examples-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit kubeflow/examples.
  kubeflow/internal-acls:
  - name: kubeflow-internal-acls-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit tests for kubeflow/internal-acls.
  kubeflow/gcp-blueprints:
  - name: kubeflow-gcp-blueprints-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit tests for kubeflow/gcp-blueprints.
  kubeflow/kubeflow:
  - name: kubeflow-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit tests for Kubeflow.
      # TODO: use a public email group
      testgrid-alert-email: kubeflow-engineering@google.com
      testgrid-num-failures-to-alert: "3"

  kubeflow/reporting:
  - name: kubeflow-reporting-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit kubeflow/reporting.
  kubeflow/website:
  - name: kubeflow-website-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit kubeflow/website.
  kubeflow/testing:
  - name: kubeflow-testing-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit kubeflow/testing.
  kubeflow/tf-operator:
  - name: kubeflow-tf-operator-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit kubeflow/tf-operator.
  kubeflow/experimental-seldon:
  - name: kubeflow-experimental-seldon-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit kubeflow/experimental-seldon.
  kubeflow/caffe2-operator:
  - name: kubeflow-caffe2-operator-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit kubeflow/caffe2-operator.
  kubeflow/kubebench:
  - name: kubeflow-kubebench-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit tests for kubeflow/kubebench.
  kubeflow/mpi-operator:
  - name: kubeflow-mpi-operator-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit tests for kubeflow/mpi-operator.
  kubeflow/chainer-operator:
  - name: kubeflow-chainer-operator-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit tests for kubeflow/chainer-operator.
  kubeflow/mxnet-operator:
  - name: kubeflow-mxnet-operator-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit kubeflow/mxnet-operator.
  kubeflow/arena:
  - name: kubeflow-arena-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit tests for kubeflow/arena.
  kubeflow/xgboost-operator:
  - name: kubeflow-xgboost-operator-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit tests for kubeflow/xgboost-operator.
