postsubmits:
  kubeflow/gcp-blueprints:
  - name: kubeflow-gcp-blueprints-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit tests for kubeflow/gcp-blueprints.
  kubeflow/testing:
  - name: kubeflow-testing-postsubmit
    cluster: kubeflow
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

    annotations:
      testgrid-dashboards: sig-big-data
      description: Postsubmit kubeflow/testing.
