presubmits:
  kubernetes-sigs/kube-storage-version-migrator:
  - name: pull-kube-storage-version-migrator-test
    decorate: true
    always_run: true
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20181019-3f9819d46-master
        command:
        - make
        - test
