presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-godeps
    run_if_changed: '^((build\/|Godeps\/|vendor\/|hack\/lib\/|hack\/.*godep|staging\/).*)$'
    path_alias: "k8s.io/kubernetes"
    decorate: true
    always_run: false
    skip_report: false
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - name: main
        command:
        - make
        image: gcr.io/k8s-testimages/kubekins-e2e:v20181205-915278e90-master
        args:
        - verify
        - WHAT="godeps staging-godeps godep-licenses"
        env:
        - name: KUBE_FORCE_VERIFY_CHECKS
          value: "Y"
        - name: KUBE_JUNIT_REPORT_DIR
          value: "${WORKSPACE}/_artifacts"
