presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-bazel-test-integration-canary
    always_run: false
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:latest-experimental
        imagePullPolicy: Always
        args:
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--scenario=kubernetes_execute_bazel"
        - "--" # end bootstrap args, scenario args below
        - "--test=//test/integration/..."
        - "--test-args=--config=integration"
        - "--timeout=60"
        resources:
          requests:
            memory: "6Gi"

    annotations:
      testgrid-dashboards: sig-testing-canaries
      testgrid-tab-name: pull-bazel-test-integration
periodics:
- name: ci-kubernetes-e2e-prow-canary
  interval: 1h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  decorate: true
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:latest-master
      imagePullPolicy: Always
      command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --check-leaked-resources
      - --cluster=canary-e2e-prow
      - --extract=ci/latest
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=25
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=65m
  annotations:
    testgrid-dashboards: sig-testing-canaries
    testgrid-tab-name: prow

- interval: 30m
  name: ci-kubernetes-e2e-gce-canary
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  decorate: true
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --check-leaked-resources
      - --check-version-skew=false
      - --cluster=canary-e2e
      - --extract=ci/k8s-stable1
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-nodes=4
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=Variable.Expansion --ginkgo.skip=\[Feature:.+\] --kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8
      - --timeout=40m
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:latest-master
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-testing-canaries
    testgrid-tab-name: gce

- interval: 2h
  name: ci-kubernetes-e2e-gce-scalability-canary
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
  decorate: true
  decoration_config:
    timeout: 140m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-big-canary
      - --extract=ci/latest
      - --gcp-nodes=100
      - --gcp-project-type=scalability-project
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:Performance\] --gather-resource-usage=true --gather-metrics-at-teardown=true --gather-logs-sizes=true --minStartupPods=8
      - --timeout=120m
      - --use-logexporter
      - --logexporter-gcs-path=gs://sig-scalability-logs/$(JOB_NAME)/$(BUILD_ID)
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:latest-master
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-testing-canaries
    testgrid-tab-name: scalability

- name: ci-kubernetes-e2e-node-canary
  interval: 1h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:latest-master
      imagePullPolicy: Always
      command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --deployment=node
      - --gcp-zone=us-west1-b
      - --node-args=--images=cos-stable-60-9592-76-0 --image-project=cos-cloud
      - --node-test-args=--kubelet-flags="--cgroups-per-qos=true --cgroup-root=/"
      - --node-tests=true
      - --provider=gce
      - --test_args=--nodes=8 --focus="\[NodeConformance\]" --skip="\[Flaky\]|\[Serial\]"
      - --timeout=90m
      env:
      - name: GOPATH
        value: /go
  annotations:
    testgrid-dashboards: sig-testing-canaries
    testgrid-tab-name: node

- name: ci-kubernetes-kubemark-100-canary
  interval: 1h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-dind-enabled: "true"
    preset-e2e-kubemark-common: "true"
  decorate: true
  decoration_config:
    timeout: 260m
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:latest-master
      imagePullPolicy: Always
      command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=kubemark-100-canary
      - --extract=ci/latest
      - --gcp-master-size=n1-standard-2
      - --gcp-node-size=n1-standard-4
      - --gcp-nodes=3
      - --gcp-zone=us-west1-b
      - --kubemark
      - --kubemark-nodes=100
      - --provider=gce
      - --test=false
      - --test_args=--ginkgo.focus=\[Feature:Performance\] --gather-resource-usage=true --gather-metrics-at-teardown=true
      - --timeout=240m
      - --use-logexporter
      - --logexporter-gcs-path=gs://sig-scalability-logs/$(JOB_NAME)/$(BUILD_ID)
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-testing-canaries
    testgrid-tab-name: kubemark
