build_image_cfg: &build_image_cfg
  decorate: true
  decoration_config:
    timeout: 45m
  always_run: true
  skip_report: false
  labels:
    preset-dind-enabled: "true"

presubmits:
  kubernetes-sigs/service-catalog:
  - name: pull-service-catalog-unit
    always_run: true
    skip_report: false
    decorate: true
    spec:
      containers:
      - image: golang:1.10
        command:
        - make
        args:
        - test-unit
        env:
        - name: NO_DOCKER
          value: "1"
  - name: pull-service-catalog-integration
    decorate: true
    decoration_config:
      timeout: 45m
    always_run: true
    skip_report: false
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190612-bf4a71f-master
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        args:
        - make
        - test-integration
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
  - name: pull-service-catalog-build-image-all-arch
    <<: *build_image_cfg
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190612-bf4a71f-master
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        args:
        - make
        - service-catalog-image-all-arch
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
  - name: pull-brokers-build-image-all-arch
    <<: *build_image_cfg
    spec:
      containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20190612-bf4a71f-master
          command:
            # generic runner script, handles DIND, bazelrc for caching, etc.
            - runner.sh
          args:
            - make
            - user-broker-image-all-arch
            - test-broker-image-all-arch
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
  - name: pull-healthcheck-build-image-all-arch
    <<: *build_image_cfg
    spec:
      containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20190612-bf4a71f-master
          command:
            # generic runner script, handles DIND, bazelrc for caching, etc.
            - runner.sh
          args:
            - make
            - healthcheck-image-all-arch
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
  - name: pull-svcat-build-image-all-arch
    <<: *build_image_cfg
    spec:
      containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20190612-bf4a71f-master
          command:
            # generic runner script, handles DIND, bazelrc for caching, etc.
            - runner.sh
          args:
            - make
            - svcat-all
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
