presubmits:
  kubernetes-sigs/cluster-api-provider-digitalocean:
  - name: pull-cluster-api-provider-digitalocean-build
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-digitalocean
    spec:
      containers:
      - image: golang:1.11
        command:
        - make
        args:
        - compile
  - name: pull-cluster-api-provider-digitalocean-test
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-digitalocean
    spec:
      containers:
      - image: golang:1.11
        command:
        - make
        args:
        - test-unit
  - name: pull-cluster-api-provider-digitalocean-verify
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-digitalocean
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20181120-dea0825e3-master
        command:
        - make
        args:
        - verify
  - name: pull-cluster-api-provider-digitalocean-lint
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-digitalocean
    labels:
        preset-service-account: "true"
        preset-bazel-scratch-dir: "true"
        preset-bazel-remote-cache-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20181120-dea0825e3-experimental
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_bazel.py
        args:
        - "--install=hack/test_requirements.txt"
        - "--test=//..."
        - "--test-args=--config=lint"
