presets:
# Credentials for using DigitalOcean test account. Used for cluster-api-provider-digitalocean/kops tests.
- labels:
    preset-do-credential: "true"
  env:
  - name: DIGITALOCEAN_ACCESS_TOKEN
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-digitalocean-token
        key: DIGITALOCEAN_ACCESS_TOKEN
  - name: DO_S3_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: spaces-digitalocean-s3
        key: access-key
  - name: DO_S3_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: spaces-digitalocean-s3
        key: secret-key
