kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: misc-mungers
    target-repo: kubernetes
  name: kubernetes-misc-mungers-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: kubernetes-misc-mungers-cache
