periodics:
- interval: 30m
  name: ci-kubernetes-e2e-gci-gce-proto
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=70
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=25
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=50m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200210-f51bb12-master
  annotations:
    testgrid-dashboards: google-gce
    testgrid-tab-name: gci-gce-proto

- interval: 24h
  name: ci-kubernetes-e2e-gci-gce-network-proxy
  decorate: true
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=70
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=ENABLE_EGRESS_VIA_KONNECTIVITY_SERVICE=true
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=25
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=9
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200210-f51bb12-master
  annotations:
    testgrid-dashboards: sig-api-machinery-network-proxy

presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-gce-network-proxy
    always_run: false
    decorate: true
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    spec:
      containers:
      - args:
        - --timeout=70
        - --bare
        - --scenario=kubernetes_e2e
        - --
        - --check-leaked-resources
        - --env=ENABLE_EGRESS_VIA_KONNECTIVITY_SERVICE=true
        - --extract=ci/latest
        - --gcp-node-image=gci
        - --gcp-zone=us-west1-b
        - --ginkgo-parallel=25
        - --provider=gce
        - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=9
        - --timeout=60m
        image: gcr.io/k8s-testimages/kubekins-e2e:v20200210-f51bb12-master
    annotations:
      testgrid-dashboards: sig-api-machinery-network-proxy
