postsubmits:
  kubernetes-sigs/cluster-api-provider-azure:
  - name: postsubmits-cluster-api-provider-azure-e2e-full-main
    decorate: true
    decoration_config:
      timeout: 2h
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
      preset-azure-cred-only: "true"
      preset-azure-anonymous-pull: "true"
    path_alias: "sigs.k8s.io/cluster-api-provider-azure"
    branches:
      - ^main$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20210928-6525112548-1.21
        command:
          - runner.sh
        args:
          - bash
          - -c
          - >-
            iptables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu &&
            ./scripts/ci-e2e.sh
        env:
          - name: GINKGO_FOCUS
            value: "Workload cluster creation"
          - name: GINKGO_SKIP
            value: ""
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-azure
      testgrid-tab-name: capz-postsubmit-capi-e2e-full-main
      testgrid-alert-email: k8s-infra-staging-cluster-api-azure@kubernetes.io
