presubmits:
  kubernetes-sigs/cluster-api-provider-azure:
  - name: pull-cluster-api-provider-azure-build
    always_run: true
    optional: true
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-azure
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190119-7f748595c-master
        command:
        - make
        args:
        - manager
        - clusterctl
  - name: pull-cluster-api-provider-azure-test
    always_run: true
    optional: true
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-azure
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190119-7f748595c-master
        command:
        - make
        args:
        - test
  - name: pull-cluster-api-provider-azure-check
    always_run: true
    optional: true
    decorate: true
    branches:
    - master
    path_alias: sigs.k8s.io/cluster-api-provider-azure
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190119-7f748595c-master
        command:
        - make
        args:
        - check
