periodics:
  - interval: 6h
    name: check-dependency-stats-periodical
    decorate: true
    decoration_config:
      timeout: 5m
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    spec:
      containers:
      - image: golang
        command:
        - /bin/bash
        args:
        - -c
        - |
          set -euo pipefail

          export WORKDIR=${ARTIFACTS:-$TMPDIR}
          export PATH=$PATH:$GOPATH/bin

          mkdir -p "${WORKDIR}"
          pushd "$WORKDIR"
          go install github.com/kubernetes-sigs/depstat@latest
          popd

          depstat stats --json > "${WORKDIR}/stats.json"
          git checkout -b base "${PULL_BASE_SHA}";
          depstat stats --json > "${WORKDIR}/stats-base.json"
          diff -s -u --ignore-all-space "${WORKDIR}"/stats-base.json "${WORKDIR}"/stats.json || true
    annotations:
      testgrid-create-test-group: "true"
      testgrid-dashboards: sig-testing-misc
      description: Generates dependency statistics by running depstat for base periodically
