# Testing to make sure things still update.
periodics:
- interval: 10m
  name: ci-test-infra-canary-echo-test
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
  annotations:
    testgrid-dashboards: sig-testing-canaries
    testgrid-tab-name: echo-test
    description: temporarily echoing things.
- name: ci-test-infra-benchmark-demo
  interval: 20m
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
    path_alias: k8s.io/test-infra
  spec:
    containers:
    - image: gcr.io/k8s-testimages/benchmarkjunit:latest
      command:
      - /benchmarkjunit
      args:
      - --log-file=$(ARTIFACTS)/benchmark-log.txt
      - --output=$(ARTIFACTS)/junit_benchmarks.xml
      - --pass-on-error
      - ./experiment/dummybenchmarks/...
  annotations:
    testgrid-alert-email: colew@google.com
    testgrid-dashboards: sig-testing-canaries
    testgrid-tab-name: benchmark-demo
    description: Demoing JUnit golang benchmark results.
- interval: 1h
  name: ci-test-infra-multiple-container-test
  decorate: true
  spec:
    containers:
    - name: test-1
      image: alpine
      command: ["/bin/echo"]
      args: ["I am first"]
    - name: test-2
      image: alpine
      command: ["/bin/sh"]
      args:
      - -c
      - "sleep 60 && echo I && sleep 60 && echo am && sleep 60 && echo second"
    - name: test-3
      image: alpine
      command: ["/bin/sh"]
      args:
      - -c
      - "sleep 120 && echo I && sleep 120 && echo am && sleep 120 && echo third"
  annotations:
    testgrid-alert-email: anthonytong@google.com
    testgrid-dashboards: sig-testing-canaries
    testgrid-tab-name: multiple-container-test
    description: echo at different times from three different containers
