postsubmits:
  kubernetes/test-infra:
  - name: post-test-infra-build-smoke
    agent: knative-build
    decorate: true
    build_spec:
      steps:
      - name: first
        image: busybox
        args: ["echo", "hello"]
      - name: second
        image: busybox
        args: ["echo", "world"]
      - name: third
        image: busybox
        args: ["cat", "config/jobs/kubernetes/test-infra/test-infra-postsubmits.yaml"]
    annotations:
      testgrid-dashboards: sig-testing-prow
      testgrid-tab-name: post-build-smoke
      description: basic postsubmit to ensure build controller works correctly

  - name: post-test-infra-bazel
    branches:
    - master
    decorate: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: launcher.gcr.io/google/bazel:0.29.1
        command:
        - hack/bazel.sh
        args:
        - test
        - --config=ci
        - --nobuild_tests_only
        - //...
    annotations:
      testgrid-dashboards: sig-testing-misc
      testgrid-tab-name: post-bazel
      description: Runs bazel test //... on the test-infra repo on each commit
