# Testing to make sure things still update.
periodics:
- interval: 10m
  name: ci-test-infra-canary-echo-test
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
  annotations:
    testgrid-dashboards: sig-testing-canaries
    testgrid-tab-name: echo-test
    description: temporarily echoing things.
- name: ci-test-infra-benchmark-demo
  interval: 20m
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
    path_alias: k8s.io/test-infra
  spec:
    containers:
    - image: gcr.io/k8s-testimages/benchmarkjunit:latest
      command:
      - /benchmarkjunit
      args:
      - --log-file=$(ARTIFACTS)/benchmark-log.txt
      - --output=$(ARTIFACTS)/junit_benchmarks.xml
      - --pass-on-error
      - ./experiment/dummybenchmarks/...
  annotations:
    testgrid-alert-email: colew@google.com
    testgrid-dashboards: sig-testing-canaries
    testgrid-tab-name: benchmark-demo
    description: Demoing JUnit golang benchmark results.
- interval: 1h
  name: ci-test-infra-larger-multiple-container-test
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
    path_alias: k8s.io/test-infra
  labels:
    preset-bazel-scratch-dir: "true"
  spec:
    containers:
    - name: benchmark-junit-container
      image: gcr.io/k8s-testimages/benchmarkjunit:latest
      command:
      - /benchmarkjunit
      args:
      - --log-file=$(ARTIFACTS)/benchmark-log.txt
      - --output=$(ARTIFACTS)/junit_benchmarks.xml
      - --pass-on-error
      - ./experiment/dummybenchmarks/...
    - name: bazel-test-container
      image: gcr.io/k8s-testimages/launcher.gcr.io/google/bazel:v20200713-e9b3d9d-test-infra
      command:
      - hack/bazel.sh
      args:
      - test
      - --config=ci
      - --nobuild_tests_only
      - //...
  annotations:
    testgrid-alert-email: anthonytong@google.com
    testgrid-dashboards: sig-testing-canaries
    testgrid-tab-name: larger-multiple-container-test
    description: combination of test-infra-bazel and ci-test-infra-benchmark-demo to test more complicated multi container behavior
