periodics:
- name: ci-test-infra-bazel
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  interval: 1h
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/launcher.gcr.io/google/bazel:v20210806-38e1be0-test-infra
      command:
      - hack/bazel.sh
      args:
      - test
      - --config=ci
      - --nobuild_tests_only
      - //...
      env:
      - name: BAZEL_FETCH_PLEASE
        value: //...
  annotations:
    testgrid-dashboards: sig-testing-misc
    testgrid-tab-name: ci-bazel
    description: Runs bazel test //... on the test-infra repo every hour

- name: metrics-kettle
  interval: 1h
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  spec:
    serviceAccountName: triage
    containers:
    - image: gcr.io/k8s-staging-test-infra/bigquery:v20210927-471c27b6e3
      args:
      - ./kettle/monitor.py
      - --stale=6
      - --table
      - k8s-gubernator:build.all
      - k8s-gubernator:build.week
      - k8s-gubernator:build.day
  annotations:
    testgrid-num-failures-to-alert: '6'
    testgrid-alert-stale-results-hours: '12'
    testgrid-dashboards: sig-testing-misc
    testgrid-alert-email: kubernetes-sig-testing-alerts@googlegroups.com, k8s-infra-oncall@google.com
    description: Monitors Kettle's BigQuery database freshness.
